"""The cat: a gray tabby with a blue collar and a little bell."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ................................
    ...................K....K.......
    ..................KBK..KPK......
    ..................KBDKKPPBK.....
    ...KK............KBBBBBBBBBK....
    ..KBBK..........KBBBBBBBBBBBK...
    .KBDK...........KDBBBBBBEEBBK...
    .KBBK...........KBDBBBBBNHBBBK..
    .KBDK...........KDBBBBBBBBWWPK..
    ..KBBK...........KBBBBBBWWWNK...
    ..KBDK.........KKKKWWBBWWWWK....
    ...KBBKKKKKKKKKBBBKRRRRKKKK.....
    ....KKBBDBBDBBDBBBBKRYRK........
    ....KBBBDBBDBBDBBBWWKKK.........
    ....KBBBBBBBBBBBBWWWK...........
    ....KBBBBBBBBBBBBWWWK...........
    .....KBBBWWWWWWWBBWWK...........
    .....KBBKDDKKKKKBBKDDK..........
    .....KBBKDDK...KBBKDDK..........
    .....KBBKDDK...KBBKDDK..........
    .....KBBKDDK...KBBKDDK..........
    .....KWWKWWK...KWWKWWK..........
    ......KK.KK.....KK.KK...........
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ................................
    ................................
    ...................K....K.......
    ..................KBK..KPK......
    ..................KBDKKPPBK.....
    ..KK.............KBBBBBBBBBK....
    .KBBK...........KBBBBBBBBBBBK...
    .KBDK...........KDBBBBBBEEBBK...
    ..KBBK..........KBDBBBBBNHBBBK..
    ..KBDK..........KDBBBBBBBBWWPK..
    ..KBBK...........KBBBBBBWWWNK...
    ..KBDK.........KKKKWWBBWWWWK....
    ...KBBKKKKKKKKKBBBKRRRRKKKK.....
    ....KKBBDBBDBBDBBBBKRYRK........
    ....KBBBDBBDBBDBBBWWKKK.........
    ....KBBBBBBBBBBBBWWWK...........
    ....KBBBBBBBBBBBBWWWK...........
    .....KBBBWWWWWWWBBWWK...........
    .....KBBKDDKKKKKBBKDDK..........
    .....KBBKDDK...KBBKDDK..........
    .....KBBKDDK...KBBKDDK..........
    .....KBBKDDK...KBBKDDK..........
    .....KWWKWWK...KWWKWWK..........
    ......KK.KK.....KK.KK...........
    ................................
""")

WALK_0 = art("""
    ................................
    ................................
    ................................
    ................................
    ...................K....K.......
    ..................KBK..KPK......
    ..................KBDKKPPBK.....
    ...KK............KBBBBBBBBBK....
    ..KBBK..........KBBBBBBBBBBBK...
    .KBDK...........KDBBBBBBEEBBK...
    .KBBK...........KBDBBBBBNHBBBK..
    .KBDK...........KDBBBBBBBBWWPK..
    ..KBBK...........KBBBBBBWWWNK...
    ..KBDK.........KKKKWWBBWWWWK....
    ...KBBKKKKKKKKKBBBKRRRRKKKK.....
    ....KKBBDBBDBBDBBBBKRYRK........
    ....KBBBDBBDBBDBBBWWKKK.........
    ....KBBBBBBBBBBBBWWWK...........
    ....KBBBBBBBBBBBBWWWK...........
    .....KBBBWWWWWWWBBWWK...........
    .....KBBKDDKKKKKDDKBBK..........
    .....KBBKDDK...KDDKBBK..........
    ....KBBK.KDDK.KDDK.KBBK.........
    ....KBBK.KDDK.KDDK.KBBK.........
    ....KWWK.KWWK.KWWK.KWWK.........
    .....KK...KK...KK...KK..........
    ................................
""")

WALK_2 = art("""
    ................................
    ................................
    ................................
    ................................
    ...................K....K.......
    ..................KBK..KPK......
    ..................KBDKKPPBK.....
    ...KK............KBBBBBBBBBK....
    ..KBBK..........KBBBBBBBBBBBK...
    .KBDK...........KDBBBBBBEEBBK...
    .KBBK...........KBDBBBBBNHBBBK..
    .KBDK...........KDBBBBBBBBWWPK..
    ..KBBK...........KBBBBBBWWWNK...
    ..KBDK.........KKKKWWBBWWWWK....
    ...KBBKKKKKKKKKBBBKRRRRKKKK.....
    ....KKBBDBBDBBDBBBBKRYRK........
    ....KBBBDBBDBBDBBBWWKKK.........
    ....KBBBBBBBBBBBBWWWK...........
    ....KBBBBBBBBBBBBWWWK...........
    .....KBBBWWWWWWWBBWWK...........
    .....KDDKBBKKKKKBBKDDK..........
    .....KDDKBBK...KBBKDDK..........
    ....KDDK.KBBK.KBBK.KDDK.........
    ....KDDK.KBBK.KBBK.KDDK.........
    ....KWWK.KWWK.KWWK.KWWK.........
    .....KK...KK...KK...KK..........
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ..............K....K............
    .............KBK..KPK...........
    .............KBDKKPPBK..........
    ............KBBBBBBBBBK.........
    ...........KBBBBBBBBBBBK........
    ...........KDBBBBBBEEBBK........
    ...........KBDBBBBBNHBBBK.......
    ...........KDBBBBBBBBWWPK.......
    ............KBBBBBBWWWNK........
    ............KKKRRRRKWWK.........
    ...........KBBKKRYRKKK..........
    ..........KBBDBBKKKWBK..........
    ..........KBBBDBBWWWWK..........
    .........KBBBBDBBWWWWK..........
    .........KBBBBBDBBWWWK..........
    ........KBBBBBBBBBWWWK..........
    ........KBBBBBBBBBBWWK..........
    .......KBBBBBBBBBBBBBK..........
    .......KBBBBBBBBKBBBBKKK........
    .......KBBBBBBBKBBKBBKBBK.......
    .......KBBBBBBBKBBKBBKBDK.......
    .......KBBBBBKKKKKKKKBBK........
    ........KBBBKBBDBBDBBBK.........
    .........KKKKKKKKKKKKK..........
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ..............K....K............
    .............KBK..KPK...........
    .............KBDKKPPBK..........
    ............KBBBBBBBBBK.........
    ...........KBBBBBBBBBBBK........
    ...........KDBBBBBBEEBBK........
    ...........KBDBBBBBNHBBBK.......
    ...........KDBBBBBBBBWWPK.......
    ............KBBBBBBWWWNK........
    ............KKKRRRRKWWK.........
    ...........KBBKKRYRKKK..........
    ..........KBBDBBKKKWBK..........
    ..........KBBBDBBWWWWK..........
    .........KBBBBDBBWWWWK..........
    .........KBBBBBDBBWWWK..........
    ........KBBBBBBBBBWWWK..........
    ........KBBBBBBBBBBWWK..........
    .......KBBBBBBBBBBBBBK..........
    .......KBBBBBBBBKBBBBK..........
    .......KBBBBBBBKBBKBBKKK........
    .......KBBBBBBBKBBKBBKBBK.......
    .......KBBBBBKKKKKKKKBDK........
    ........KBBBKBBDBBDBBBK.........
    .........KKKKKKKKKKKKK..........
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ................................
    ................................
    ...................K....K.......
    ..................KBK..KPK......
    ..................KBDKKPPBK.....
    ...KK............KBBBBBBBBBK....
    ..KBBK..........KBBBBBBBBBBBK...
    .KBDK...........KDBBBBBBEEBBK...
    .KBBK...........KBDBBBBBNHBBBK..
    .KBDK...........KDBBBBBBBBWWPK..
    ..KBBK...........KBBBBBBWWWNK...
    ..KBDK.........KKKKWWBBWWWWK....
    ...KBBKKKKKKKKKBBBKRRRRKKKK.....
    ....KKBBDBBDBBDBBBBKRYRK........
    ....KBBBDBBDBBDBBBWWKKK.........
    ....KBBBBBBBBBBBBWWWK...........
    ....KBBBBBBBBBBBBWWWK...........
    .....KBBBWWWWWWWBBWWK...........
    .....KBBKDDKKKKKBBKDDK..........
    ....KBBKDDK.....KBBKDDK.........
    ...KBBKDDK.......KBBKDDK........
    ..KWWKWWK.........KWWKWWK.......
    ...KK.KK...........KK.KK........
    ................................
    ................................
""")

CARRIED_B = art("""
    ................................
    ................................
    ................................
    ................................
    ...................K....K.......
    ..................KBK..KPK......
    ..................KBDKKPPBK.....
    .................KBBBBBBBBBK....
    ................KBBBBBBBBBBBK...
    ................KDBBBBBBEEBBK...
    ................KBDBBBBBNHBBBK..
    ................KDBBBBBBBBWWPK..
    .................KBBBBBBWWWNK...
    ...............KKKKWWBBWWWWK....
    ......KKKKKKKKKBBBKRRRRKKKK.....
    .....KBBDBBDBBDBBBBKRYRK........
    ...KKBBBDBBDBBDBBBWWKKK.........
    ..KBBKBBBBBBBBBBBWWWK...........
    ..KBDKBBBBBBBBBBBWWWK...........
    ..KBKKBBBWWWWWWWBBWWK...........
    .KBDKKKBBKDDKKKKBBKDDK..........
    .KBK..KWWKWWK..KWWKWWK..........
    .KBK...KK.KK....KK.KK...........
    ..K.............................
    ................................
    ................................
    ................................
""")

CAT = Species(
    key="cat",
    label=QT_TRANSLATE_NOOP("Species", "Cat"),
    palette={
        "K": "#2d2a33",  # outline
        "B": "#a3a8b0",  # gray fur
        "D": "#6c717b",  # tabby stripes, far ear and legs
        "W": "#f2efe9",  # white chest, paws, muzzle
        "N": "#25222a",  # pupil, mouth
        EYE: "#25222a",
        EYE_SHINE: "#ffffff",
        "P": "#f39bb0",  # nose, inner ear
        "R": "#3b7dd8",  # collar
        "Y": "#f5c542",  # bell
    },
    animations={
        Activity.STANDING: Animation((STAND_A, STAND_B), fps=1.5),  # twitching its tail
        Activity.WALKING: Animation((WALK_0, STAND_A, WALK_2, STAND_B), fps=7),
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # tail wrapped around its paws
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),  # kicking
    },
    gait=Gait(speed=40, max_slope=0.4, distance=(80, 320)),
)
