"""The cat: a gray tabby with a blue collar and a little bell."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    ......KK...........KBPKKKPBK....
    .....KBBK...........KKDBDBK.....
    ....KBBBK...........KBBDBBBK....
    ...KDBBK...........KBBBBBEEBK...
    ...KDDK............KBBBBBNHBK...
    ...KBBK............KBBBBBBWWPK..
    ...KBBK............KBBBBBWWWWK..
    ...KDDBK.KKKKKKKKKK.KRBBBWWNK...
    ....KBBBKDBBDBBDBBBKWWRRRBKK....
    .....KBBBDBBDBBDBBBWWWWYKK......
    ......KBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    ......KBBBWWWWWWWWBBWWK.........
    .......KBBWWWWWWWWBBDDK.........
    .......KBBKDDKKKKKBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KWWKWWK...KWWWWK.........
    ........KK.KK.....KKKK..........
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    .....KK............KBPKKKPBK....
    ....KBBK............KKDBDBK.....
    ...KBBBK............KBBDBBBK....
    ...KBBK............KBBBBBEEBK...
    ...KDDK............KBBBBBNHBK...
    ...KBBK............KBBBBBBWWPK..
    ...KBBK............KBBBBBWWWWK..
    ...KDDBK.KKKKKKKKKK.KRBBBWWNK...
    ....KBBBKDBBDBBDBBBKWWRRRBKK....
    .....KBBBDBBDBBDBBBWWWWYKK......
    ......KBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    ......KBBBWWWWWWWWBBWWK.........
    .......KBBWWWWWWWWBBDDK.........
    .......KBBKDDKKKKKBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KWWKWWK...KWWWWK.........
    ........KK.KK.....KKKK..........
    ................................
""")

WALK_0 = art("""
    ................................
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    ......KK...........KBPKKKPBK....
    .....KBBK...........KKDBDBK.....
    ....KBBBK...........KBBDBBBK....
    ...KDBBK...........KBBBBBEEBK...
    ...KDDK............KBBBBBNHBK...
    ...KBBK............KBBBBBBWWPK..
    ...KBBK............KBBBBBWWWWK..
    ...KDDBK.KKKKKKKKKK.KRBBBWWNK...
    ....KBBBKDBBDBBDBBBKWWRRRBKK....
    .....KBBBDBBDBBDBBBWWWWYKK......
    ......KBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    ......KBBBWWWWWWWWBBWWK.........
    .......KBBWWWWWWWWBBDDK.........
    .......KBBKDDKKKKKBBDDK.........
    .......KBBKKDDK..KBBDK..........
    ......KBBK.KDDK...KBBK..........
    ......KBBK.KDDK...KBBK..........
    ......KWWK.KWWK...KWWK..........
    .......KK...KK.....KK...........
    ................................
""")

WALK_1 = art("""
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    ......KK...........KBPKKKPBK....
    .....KBBK...........KKDBDBK.....
    ....KBBBK...........KBBDBBBK....
    ...KDBBK...........KBBBBBEEBK...
    ...KDDK............KBBBBBNHBK...
    ...KBBK............KBBBBBBWWPK..
    ...KBBK............KBBBBBWWWWK..
    ...KDDBK.KKKKKKKKKK.KRBBBWWNK...
    ....KBBBKDBBDBBDBBBKWWRRRBKK....
    .....KBBBDBBDBBDBBBWWWWYKK......
    ......KBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    ......KBBBWWWWWWWWBBWWK.........
    .......KBBWWWWWWWWBBDDK.........
    .......KBBKDDKKKKKBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKWWK...KWWDDK.........
    .......KWWKKK.....KKWWK.........
    ........KK..........KK..........
    ................................
""")

WALK_2 = art("""
    ................................
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    .....KK............KBPKKKPBK....
    ....KBBK............KKDBDBK.....
    ...KBBBK............KBBDBBBK....
    ...KBBK............KBBBBBEEBK...
    ...KDDK............KBBBBBNHBK...
    ...KBBK............KBBBBBBWWPK..
    ...KBBK............KBBBBBWWWWK..
    ...KDDBK.KKKKKKKKKK.KRBBBWWNK...
    ....KBBBKDBBDBBDBBBKWWRRRBKK....
    .....KBBBDBBDBBDBBBWWWWYKK......
    ......KBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    ......KBBBWWWWWWWWBBWWK.........
    .......KBBWWWWWWWWBBDDK.........
    .......KBBKDDKKKKKBBDDK.........
    .......KBBDDK....KBBKDDK........
    ........KBBDK...KBBKKDDK........
    ........KBBDK...KBBKKDDK........
    ........KWWWK...KWWKKWWK........
    .........KKK.....KK..KK.........
    ................................
""")

WALK_3 = art("""
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    .....KK............KBPKKKPBK....
    ....KBBK............KKDBDBK.....
    ...KBBBK............KBBDBBBK....
    ...KBBK............KBBBBBEEBK...
    ...KDDK............KBBBBBNHBK...
    ...KBBK............KBBBBBBWWPK..
    ...KBBK............KBBBBBWWWWK..
    ...KDDBK.KKKKKKKKKK.KRBBBWWNK...
    ....KBBBKDBBDBBDBBBKWWRRRBKK....
    .....KBBBDBBDBBDBBBWWWWYKK......
    ......KBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    .....KBBBBBBBBBBBBBWWWWK........
    ......KBBBWWWWWWWWBBWWK.........
    .......KBBWWWWWWWWBBDDK.........
    .......KBBKDDKKKKKBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KBBKDDK...KBBDDK.........
    .......KWWKDDK...KBBWWK.........
    ........KKKWWK...KWWKK..........
    ...........KK.....KK............
    ................................
""")

SIT_A = art("""
    ...............KBK...KBK........
    ...............KBBK.KBBK........
    ...............KBPKKKPBK........
    ................KKDBDBK.........
    ................KBBDBBBK........
    ...............KBBBBBEEBK.......
    ...............KBBBBBNHBK.......
    ...............KBBBBBBWWPK......
    ...............KBBBBBWWWWK......
    ..............KBBRBBBWWNK.......
    ............KKBBBBRRRBKK........
    ...........KDDBBBBBYWK..........
    ............KBBBBBWWWK..........
    ............KBBBBBWWWWK.........
    ...........KDDBBBBWWWWK.........
    ............KBBBBBWWWWK.........
    ...........KKBBBBBWWBBK.........
    ..........KBBBBBBBBWBBK.........
    .........KBBBBBBBBBBBBK.........
    ..KK....KBBDDBBBBBBBBBK.........
    .KDDK...KBBBBBBBBBBDBBK.........
    .KDDK...KBDDBBBBBBDDBBK.........
    .KBBKKKKKBBBBBBBBKDDBBK.........
    .KBBBBDDBBBBBBBBKKDDBBK.........
    ..KKBBDDBBBBKKWWWKWWWWK.........
    ....KKKKKKKK..KKK.KKKK..........
    ................................
""")

SIT_B = art("""
    ...............KBK...KBK........
    ...............KBBK.KBBK........
    ...............KBPKKKPBK........
    ................KKDBDBK.........
    ................KBBDBBBK........
    ...............KBBBBBEEBK.......
    ...............KBBBBBNHBK.......
    ...............KBBBBBBWWPK......
    ...............KBBBBBWWWWK......
    ..............KBBRBBBWWNK.......
    ............KKBBBBRRRBKK........
    ...........KDDBBBBBYWK..........
    ............KBBBBBWWWK..........
    ............KBBBBBWWWWK.........
    ...........KDDBBBBWWWWK.........
    ............KBBBBBWWWWK.........
    ...........KKBBBBBWWBBK.........
    ..........KBBBBBBBBWBBK.........
    .KK......KBBBBBBBBBBBBK.........
    KBBK....KBBDDBBBBBBBBBK.........
    KBBK....KBBBBBBBBBBDBBK.........
    .KDDK...KBDDBBBBBBDDBBK.........
    .KDDBKKKKBBBBBBBBKDDBBK.........
    ..KBBBDDBBBBBBBBKKDDBBK.........
    ...KBBDDBBBBKKWWWKWWWWK.........
    ....KKKKKKKK..KKK.KKKK..........
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    ...................KBPKKKPBK....
    ....................KKDBDBK.....
    ....................KBBDBBBK....
    ...................KBBBBBEEBK...
    ...................KBBBBBNHBK...
    ...................KBBBBBBWWPK..
    ...................KBBBBBWWWWK..
    .........KKKKKKKKKK.KRBBBWNNK...
    ......KKKDBBDBBDBBBKWWRRRBKPK...
    .....KBBBDBBDBBDBBBWWWWYKK.K....
    ....KBBBBBBBBBBBBBBWWWWK........
    ...KDDBBBBBBBBBBBBBWWWWK........
    ...KBBBBBBBBBBBBBBBWWWWK........
    ...KBBKBBBWWWWWWWWBBWWK.........
    ...KDDKBBBWWWWWWWWBBBK..........
    ...KDBBBBKKKDDKKKKKBBK..........
    ....KBBBBK.KDDK...KBBK..........
    .....KKBBK.KDDK...KBBK..........
    ......KBBK.KDDK...KBBK..........
    ......KBBK.KDDK...KBBK..........
    ......KWWK.KWWK...KWWK..........
    .......KK...KK.....KK...........
""")

CARRIED_B = art("""
    ................................
    ................................
    ....................K.....K.....
    ...................KBK...KBK....
    ...................KBBK.KBBK....
    ...................KBPKKKPBK....
    ....................KKDBDBK.....
    ....................KBBDBBBK....
    ...................KBBBBBEEBK...
    ...................KBBBBBNHBK...
    ...................KBBBBBBWWPK..
    ...................KBBBBBWWWWK..
    .........KKKKKKKKKK.KRBBBWNNK...
    ......KKKDBBDBBDBBBKWWRRRBKPK...
    .....KBBBDBBDBBDBBBWWWWYKK.K....
    ....KBBBBBBBBBBBBBBWWWWK........
    ...KDDBBBBBBBBBBBBBWWWWK........
    ...KBBBBBBBBBBBBBBBWWWWK........
    ...KBBKBBBWWWWWWWWBBWWDK........
    ...KDDKKKBBWWWWWWBBBKDDK........
    ...KDBBKKBBDKKKKKBBKKDDK........
    ....KBBKKBBDK...KBBKKDDK........
    .....KK.KBBDK...KBBKKDDK........
    ........KBBDK...KBBKKDDK........
    ........KBBDK...KBBKKDDK........
    ........KWWWK...KWWKKWWK........
    .........KKK.....KK..KK.........
""")

CAT = Species(
    key="cat",
    label="Cat",
    palette={
        "K": "#2d2a33",  # outline
        "B": "#a3a8b0",  # gray fur
        "D": "#6c717b",  # tabby stripes, far legs
        "W": "#f2efe9",  # white chest, paws, muzzle
        "N": "#25222a",  # pupil, mouth
        EYE: "#9ccc3c",  # green iris
        EYE_SHINE: "#ffffff",
        "P": "#f39bb0",  # nose, inner ears
        "R": "#3b7dd8",  # collar
        "Y": "#f5c542",  # bell
    },
    animations={
        Activity.STANDING: Animation((STAND_A, STAND_B), fps=1.5),  # twitching its tail
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_3), fps=7),
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),
    },
    gait=Gait(speed=40, max_slope=0.4, distance=(80, 320)),
)
