"""The chameleon: a veiled chameleon that walks slowly and changes color while it keeps still.

Its colorings are whole palettes: PetWindow paints each column in one of them, and color_change.py
runs a wave of a new one from the head to the tail when it stops, and back to green when it walks.
"""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLLEELKBBK
    ......KYBSBYBBBYBBBBYBKLLNHLKBBK
    .....KDYBBBYBBBYBBBBYBKLLLLLKBBK
    .....KDYBBBBYBBBYBBBBYBKLLLKBBBK
    ....KDDBYBBBYBSBYBBBBYBBKKKNNNNK
    ....KDDDYBSBYBBBYBBBBBBBNOOOOOOK
    ...KBDDDDDDDDDDDDDDBBBBBBBBDKK..
    ...KBDDKLLLLLLLLLLLLLLLLLDK.....
    ..KBDDKKKKKKBDKFFKKKBDKFFKK.....
    ..KBDK....KBDKFFK.KBDKFFK.......
    ..KBKKKK.KBDKFFK.KBDKFFK........
    ..KBKYBBKKBDKFFK.KBDKFFK........
    ..KYKBKBK.KBDKFFK.KBDKFFK.......
    ..KBKKKBK..KBDKFFK.KBDKFFK......
    ...KBBYBK.KBKBDKFFKBKBDKFFK.....
    ....KKKK...K.KK.KK.K.KK.KK......
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLEELLKBBK
    ......KYBSBYBBBYBBBBYBKLNHLLKBBK
    .....KDYBBBYBBBYBBBBYBKLLLLLKBBK
    .....KDYBBBBYBBBYBBBBYBKLLLKBBBK
    ....KDDBYBBBYBSBYBBBBYBBKKKNNNNK
    ....KDDDYBSBYBBBYBBBBBBBNOOOOOOK
    ...KBDDDDDDDDDDDDDDBBBBBBBBDKK..
    ...KBDDKLLLLLLLLLLLLLLLLLDK.....
    ..KBDDKKKKKKBDKFFKKKBDKFFKK.....
    ..KBDK....KBDKFFK.KBDKFFK.......
    ..KBKKKK.KBDKFFK.KBDKFFK........
    ..KBKYBBKKBDKFFK.KBDKFFK........
    ..KYKBKBK.KBDKFFK.KBDKFFK.......
    ..KBKKKBK..KBDKFFK.KBDKFFK......
    ...KBBYBK.KBKBDKFFKBKBDKFFK.....
    ....KKKK...K.KK.KK.K.KK.KK......
    ................................
""")

WALK_A = art("""
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLLEELKBBK
    ......KYBSBYBBBYBBBBYBKLLNHLKBBK
    .....KDYBBBYBBBYBBBBYBKLLLLLKBBK
    .....KDYBBBBYBBBYBBBBYBKLLLKBBBK
    ....KDDBYBBBYBSBYBBBBYBBKKKNNNNK
    ....KDDDYBSBYBBBYBBBBBBBNOOOOOOK
    ...KBDDDDDDDDDDDDDDBBBBBBBBDKK..
    ...KBDDKLLLLLLLLLLLLLLLLLDK.....
    ..KBDDKKKKKKBDKFFKKKBDKFFKK.....
    ..KBDK....KBDKKFFK.KBDKFFK......
    ..KBKKKK.KBDK..KFFK.KBDKK.......
    ..KBKYBBKKBDK...KFFK.KBDK.......
    ..KYKBKBKKBDK....KFFKKKBDK......
    ..KBKKKBKKBDK....KFFKKKBDK......
    ...KBBYBKBKBDK..KFKFFKBKBDK.....
    ....KKKK.K.KK....K.KKKKKKK......
    ................................
""")

WALK_B = art("""
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLLEELKBBK
    ......KYBSBYBBBYBBBBYBKLLNHLKBBK
    .....KDYBBBYBBBYBBBBYBKLLLLLKBBK
    .....KDYBBBBYBBBYBBBBYBKLLLKBBBK
    ....KDDBYBBBYBSBYBBBBYBBKKKNNNNK
    ....KDDDYBSBYBBBYBBBBBBBNOOOOOOK
    ...KBDDDDDDDDDDDDDDBBBBBBBBDKK..
    ...KBDDKLLLLLLLLLLLLLLLLLDK.....
    ..KBDDKKKKKKBDKFFKKKBDKFFKK.....
    ..KBDK.....KBDKFFKKBDKKFFK......
    ..KBKKKK....KBDKK.KBDK.KFFK.....
    ..KBKYBBK...KBDKKKBDK...KFFK....
    ..KYKBKBK...KBDKKKBDK....KFFK...
    ..KBKKKBK...KBDKKKBDK....KFFK...
    ...KBBYBK..KBKBDKBKBDK..KFKFFK..
    ....KKKK....KKKKKK.KK....K.KK...
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLLEELKBBK
    .....KKYBSBYBBBYBBBBYBKLLNHLKBBK
    ...KKBDYBBBYBBBYBBBBYBKLLLLLKBBK
    ..KBDKKKBBBKKBBBYBKKBYBKLLLKBBBK
    ..KBKYBBKBKBDKSBYKBDKYBBKKKNNNNK
    ..KYKBKBKKBDKBBBKBDKBBBBNOOOOOOK
    ..KBKKKBKBDKDKKKBDKKKBKKBBBDKK..
    ...KBBYBKBBBKBDKBBBBBKBDKDFKFK..
    ....KKKK.KKKKKKKKKKKKKKKKKK.K...
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLEELLKBBK
    .....KKYBSBYBBBYBBBBYBKLNHLLKBBK
    ...KKBDYBBBYBBBYBBBBYBKLLLLLKBBK
    ..KBDKKKBBBKKBBBYBKKBYBKLLLKBBBK
    ..KBKYBBKBKBDKSBYKBDKYBBKKKNNNNK
    ..KYKBKBKKBDKBBBKBDKBBBBNOOOOOOK
    ..KBKKKBKBDKDKKKBDKKKBKKBBBDKK..
    ...KBBYBKBBBKBDKBBBBBKBDKDFKFK..
    ....KKKK.KKKKKKKKKKKKKKKKKK.K...
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLLEELKBBK
    ......KYBSBYBBBYBBBBYBKLLNHLKBBK
    .....KDYBBBYBBBYBBBBYBKLLLLLKBBK
    .....KDYBBBBYBBBYBBBBYBKLLLKBBBK
    ....KDDBYBBBYBSBYBBBBYBBKKKNNNNK
    ....KDDDYBSBYBBBYBBBBBBBNOOOOOOK
    ...KBDDDDDDDDDDDDDDBBBBBBBBDKK..
    ...KBDDKLLLLLLLLLLLLLLLLLDK.....
    ..KBDDKKKKKKBDKFFKKKBDKFFKK.....
    ..KBDK.....KBDKFFK.KBDKFFK......
    ..KBKKKK...KBDKFFK.KBDKFFK......
    ..KBKYBBK..KBDKFFK.KBDKFFK......
    ..KYKBKBK..KBDKKFFKKBDKKFFK.....
    ..KBKKKBK.KBKBDKKFKBKBDKKFFK....
    ...KBBYBK..K.KKK.KKK.KKK.KK.....
    ....KKKK........................
    ................................
""")

CARRIED_B = art("""
    ................................
    ................................
    ................................
    ......................KK........
    .....................KLBKK......
    ....................KLBYBBKK....
    .............KKK...KLBBYBBBBKK..
    ...........KKBBYKKKLBBBBYBBBBBK.
    .........KKYBBBYBBBLBBBBKKKBBBK.
    ........KBBYBBBYBBBYBBBKLLLKBBK.
    .......KBBBYBSBYBSBBYBKLLEELKBBK
    ......KYBSBYBBBYBBBBYBKLLNHLKBBK
    .....KDYBBBYBBBYBBBBYBKLLLLLKBBK
    .....KDYBBBBYBBBYBBBBYBKLLLKBBBK
    ....KDDBYBBBYBSBYBBBBYBBKKKNNNNK
    ....KDDDYBSBYBBBYBBBBBBBNOOOOOOK
    ...KBDDDDDDDDDDDDDDBBBBBBBBDKK..
    ...KBDDKLLLLLLLLLLLLLLLLLDK.....
    ..KBDDKKKKKKBDKFFKKKBDKFFKK.....
    ..KBDK.....KBDKFFK.KBDKFFK......
    ..KBKKKK...KBDKFFK.KBDKFFK......
    ..KBKYBBK...KBDKFK..KBDKFK......
    ..KYKBKBK...KBDKFK..KBDKFK......
    ..KBKKKBK..KBKBDKFKKBKBDKFK.....
    ...KBBYBK...K.KKKK..K.KKKK......
    ....KKKK........................
    ................................
""")


def coloring(  # noqa: PLR0913 - one color per part of the body
    *, body: str, shade: str, far: str, light: str, bands: str, spots: str, lip: str
) -> dict[str, str]:
    """A palette of the chameleon: only the outline, the pupil and the eye's shine never change."""
    return {
        "K": "#16261a",  # outline
        "B": body,
        "D": shade,  # the lower flank and the near legs' back
        "F": far,  # the far legs
        "L": light,  # belly, the rim of the casque and the eye's turret
        "Y": bands,
        "S": spots,
        "O": lip,  # the stripe along the lower jaw
        "N": "#0c140e",  # mouth, pupil
        EYE: light,  # the turret above the pupil, which a blink covers in the body color
        EYE_SHINE: "#ffffff",
    }


GREEN = coloring(
    body="#3fa34d",
    shade="#2b7a3a",
    far="#1f5a2c",
    light="#a6d86a",
    bands="#e3d44a",
    spots="#7fd6c0",
    lip="#f0b43c",
)
TURQUOISE = coloring(
    body="#1d9c9c",
    shade="#147070",
    far="#0e5050",
    light="#8fdcc8",
    bands="#f4d03f",
    spots="#f28c38",
    lip="#f4d03f",
)
YELLOW = coloring(
    body="#c4b53a",
    shade="#917f24",
    far="#6a5c18",
    light="#efe28a",
    bands="#f08a3c",
    spots="#36b0a8",
    lip="#f06a3c",
)
PURPLE = coloring(
    body="#7a5cc8",
    shade="#5a42a0",
    far="#3f2e78",
    light="#b9a6ee",
    bands="#d4e04a",
    spots="#5ab4ec",
    lip="#e8c84a",
)

CHAMELEON = Species(
    key="chameleon",
    label=QT_TRANSLATE_NOOP("Species", "Chameleon"),
    palette=GREEN,
    animations={
        # Keeping still, and now and then rolling its eye back.
        Activity.STANDING: Animation((STAND_A,) * 3 + (STAND_B,) * 2 + (STAND_A,) * 3, fps=1),
        # A slow walk: diagonal pairs of legs step together, near front with far hind.
        Activity.WALKING: Animation((WALK_A, STAND_A, WALK_B, STAND_A), fps=3),
        # Resting with its belly on the ground, the legs folded at its sides.
        Activity.SITTING: Animation((SIT_A,) * 3 + (SIT_B,) * 2 + (SIT_A,) * 3, fps=1),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=3),  # the legs dangling
    },
    gait=Gait(speed=20, max_slope=0.4, distance=(60, 200), rest=(4.0, 8.0)),
    colorings=(TURQUOISE, YELLOW, PURPLE),
)
