"""The chicken: a golden brown hen that scratches the ground and pecks at it when it stops."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    .............KOK...KYK..........
    .............KOK...KYKK.........
    ............KOOOK.KYYYYK........
    ............KKKKK.KKKKKK........
    ................................
""")

# Scratching the ground: the near foot lifted, reaching forward...
SCRATCH_LIFT = art("""
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    .............KOK...KYKKKK.......
    .............KOK...KKYYYYK......
    ............KOOOK...KKKKKK......
    ............KKKKK...............
    ................................
""")

# ...then raked back along the ground...
SCRATCH_RAKE = art("""
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    .............KOK..KYK...........
    .............KOK.KYKK...........
    ............KOOOKYYYYK..........
    ............KKKKKKKKKK..........
    ................................
""")

# ...and the far foot raked back behind it.
SCRATCH_FAR = art("""
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    ............KOK....KYK..........
    ...........KOK.....KYKK.........
    ..........KOOOK...KYYYYK........
    ..........KKKKK...KKKKKK........
    ................................
""")

# Tipped forward, looking at the ground...
LOOK_DOWN = art("""
    ................................
    ................................
    ................................
    ................................
    .KK.............................
    .KDKK...........................
    .KTDDK..........................
    ..KTDDK.........................
    ..KDTDDK..................KK....
    ..KDDTDDKK...............KRRKK..
    ...KDDTDDBKKKKKKK.......KBBRRRK.
    ...KDDDDBBBBBBBBBKKKKKKKBBBBBRRK
    ....KDDBBBBBBBBBBBBBBBBBBBBBBBRK
    ....KDBBBBDDDDDDDBBBBBBBBBEEBBRK
    .....KBBBDDDDDDDDDDBBBBBBBNHBBK.
    ......KBBDDDDDDDDDDBBBBBRBBBBYK.
    .......KBBDBDBDDDDBBBBBRRBBBYYK.
    ........KKBBBBBBBBBBBBBKRRKYYK..
    ..........KKBBBBBBBBBBKKKKKKYK..
    ............KKBBBBBBBKK.....K...
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    .............KOK...KYK..........
    .............KOK...KYKK.........
    ............KOOOK.KYYYYK........
    ............KKKKK.KKKKKK........
    ................................
""")

# ...and pecking at it, the beak on the ground line.
PECK = art("""
    ................................
    ................................
    ................................
    ................................
    .KK.............................
    .KDKK...........................
    .KTDDK..........................
    ..KTDDK.........................
    ..KDTDDK........................
    ..KDDTDDKK......................
    ...KDDTDDBKKKKKKK...............
    ...KDDDDBBBBBBBBBKKKK...........
    ....KDDBBBBBBBBBBBBBBKK.........
    ....KDBBBBDDDDDDDBBBBBBKK.......
    .....KBBBDDDDDDDDDDBBBBBBK......
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KBBDBDBDDDDBBBBBBBBBKK...
    ........KKBBBBBBBBBBBBBBBBBBBKKK
    ..........KKBBBBBBBBBBBBBBBBBRRK
    ............KKBBBBBBBKBBBBBBBBRK
    ............KBBBKKKBBBKKBBEEBBRK
    .............KOK...KYK.KBBNHBBK.
    .............KOK...KYK.KRBBBYK..
    .............KOK...KYKKKRRBYYK..
    ............KOOOK.KYYYYKKRKYK...
    ............KKKKK.KKKKKK.K.K....
    ................................
""")

# Walking: short steps, the head thrust a pixel forward as each foot lands.
WALK_0 = art("""
    ................................
    ......................KK.K......
    .....................KRRKRK.....
    ....................KRRRRRRK....
    ...................KBBBBBBBBK...
    ..................KBBBBBBEEBK...
    ..................KBBBBBBNHBYK..
    .KK...............KBBBBBBBBYYYK.
    .KDKK..............KBBBBBBRKKK..
    .KTDDK.............KBBBBBRRRK...
    ..KTDDK...........KBBBBBBBRRK...
    ..KDTDDK.........KBBBBBBBBBK....
    ..KDDTDDKK....KKKBBBBBBBBBBK....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    ............KOK.....KYK.........
    ............KOK.....KYKK........
    ...........KOOOK...KYYYYK.......
    ...........KKKKK...KKKKKK.......
    ................................
""")

WALK_1 = art("""
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    ..............KOK..KYK..........
    ..............KOOK.KYK..........
    ...............KKK.KYKK.........
    ..................KYYYYK........
    ..................KKKKKK........
    ................................
""")

WALK_2 = art("""
    ................................
    ......................KK.K......
    .....................KRRKRK.....
    ....................KRRRRRRK....
    ...................KBBBBBBBBK...
    ..................KBBBBBBEEBK...
    ..................KBBBBBBNHBYK..
    .KK...............KBBBBBBBBYYYK.
    .KDKK..............KBBBBBBRKKK..
    .KTDDK.............KBBBBBRRRK...
    ..KTDDK...........KBBBBBBBRRK...
    ..KDTDDK.........KBBBBBBBBBK....
    ..KDDTDDKK....KKKBBBBBBBBBBK....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KYK...KOK..........
    ............KYK.....KOK.........
    ............KYKK....KOK.........
    ...........KYYYYK..KOOOK........
    ...........KKKKKK..KKKKK........
    ................................
""")

WALK_3 = art("""
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    .............KOK...KYYK.........
    .............KOK...KKYYK........
    .............KOK....KKKK........
    ............KOOOK...............
    ............KKKKK...............
    ................................
""")

# Settled on the ground like a hen on her nest, the legs tucked under.
SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KKKKKKKKKKK.........
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBK....
    .................KBBBBBBNHBYK...
    .KK..............KBBBBBBBBYYYK..
    .KDKK.............KBBBBBBRKKK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDKKK....KKKBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBDDDDDDBBBBBBBBBK....
    .....KDBBBDDDDDDDDDDBBBBBBK.....
    ......KBBDDDDDDDDDDBBBBBBBK.....
    .......KKBDBDBDDDDBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KKKKKKKKKKK.........
    ................................
""")

# Picked up, it squawks and flaps: the wing raised from the shoulder in a short round fan...
CARRIED_A = art("""
    ................................
    .........K.K.K.......KK.K.......
    ........KDKDKDKK....KRRKRK......
    .......KDTDTDTDDK..KRRRRRRK.....
    .......KDDTDTDDDK.KBBBBBBBBK....
    ........KDDDDDDDDKBBBBBBEEBKK...
    .........KBDDDDDDKBBBBBBNHBYYK..
    .KK.......KBBDDDDKBBBBBBBBBNKK..
    .KDKK......KBBBDDDKBBBBBBRYYK...
    .KTDDK......KBBBBDKBBBBBRRRK....
    ..KTDDK......KBBBKBBBBBBBRRK....
    ..KDTDDK......KBBBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKBBBBBBBBBBBBBK....
    ...KDDDDBBBBBBBBBBBBBBBBBBBK....
    ....KDDBBBBBBBBBBBBBBBBBBBBK....
    .....KDBBBBBBBBBBBBBBBBBBBK.....
    ......KBBBBBBBBBBBBBBBBBBBK.....
    .......KKBBBBBBBBBBBBBBBBK......
    .........KKKBBBBBBBBBBBKK.......
    ............KBBBKKKBBBK.........
    .............KOK...KYK..........
    .............KOK...KYK..........
    .............KOK...KYK..........
    ............KOKOK.KYKYK.........
    .............K.K...K.K..........
    ................................
""")

# ...and lowered, the same fan hanging back behind the legs, its tip closed in a round
# edge (feather tips pointing down would look like a claw).
CARRIED_B = art("""
    ................................
    .....................KK.K.......
    ....................KRRKRK......
    ...................KRRRRRRK.....
    ..................KBBBBBBBBK....
    .................KBBBBBBEEBKK...
    .................KBBBBBBNHBYYK..
    .KK..............KBBBBBBBBBNKK..
    .KDKK.............KBBBBBBRYYK...
    .KTDDK............KBBBBBRRRK....
    ..KTDDK..........KBBBBBBBRRK....
    ..KDTDDK........KBBBBBBBBBK.....
    ..KDDTDDKK....KKBBBBBBBBBBK.....
    ...KDDTDDBKKKKKBBBBBBBBBBBBK....
    ...KDDDDBBBBBKBBBBBBBBBBBBBK....
    ....KDDBBBBKBBBBDBBBBBBBBBBK....
    .....KDBBBKBBBDDDBBBBBBBBBK.....
    ......KBKBBDDDDBBBBBBBBBBBK.....
    .......KBDDDDDDBBBBBBBBBBK......
    .....KKDTDDTDDDBBBBBBBBKK.......
    ....KDDTDDTDDKBBKKKBBBK.........
    ....KDTDDTDDKKOK...KYK..........
    .....KDDTDDK.KOK...KYK..........
    ......KKKKK..KOK...KYK..........
    ............KOKOK.KYKYK.........
    .............K.K...K.K..........
    ................................
""")


# At each stop it scratches the ground, the near foot and then the far one, looks down and
# pecks twice, then stands a moment.
SCRATCHING = (SCRATCH_LIFT, SCRATCH_RAKE, STAND_A, SCRATCH_FAR, SCRATCH_LIFT, SCRATCH_RAKE, STAND_A)
PECKING = (LOOK_DOWN, LOOK_DOWN, PECK, LOOK_DOWN, PECK, LOOK_DOWN)

CHICKEN = Species(
    key="chicken",
    label=QT_TRANSLATE_NOOP("Species", "Chicken"),
    palette={
        "K": "#2e1b10",  # outline
        "B": "#c98b4a",  # golden brown feathers
        "D": "#8f5a2b",  # darker brown: wing, tail, the flight feathers of an open wing
        "T": "#5e3a1b",  # darkest brown: lines between the tail and flight feathers
        "R": "#d8352b",  # comb and wattles
        "Y": "#f2b43c",  # beak, near leg
        "O": "#c98a2a",  # far leg
        "N": "#1d120b",  # pupil, open beak
        EYE: "#1d120b",
        EYE_SHINE: "#ffffff",
    },
    animations={
        Activity.STANDING: Animation((STAND_A,) * 3 + SCRATCHING + PECKING + (STAND_A,) * 6, fps=6),
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_3), fps=8),
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # breathing
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=8),  # squawking, flapping
    },
    # Short walks, and stops long enough to scratch and peck (the routine takes 3.7 s).
    gait=Gait(speed=35, max_slope=0.4, distance=(60, 240), rest=(3.0, 7.0)),
)
