"""The cockatiel: gray, with a yellow face and crest and orange cheeks, that flies around."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................KK..............
    ...............KBBKK............
    ................KKYBK...........
    ..................KYBK..........
    ...................KYBK.........
    ...................KYBBK........
    .................KKKYBBBK.......
    ...............KKGGBBBBBK.......
    ..............KGGBBBBBBBBK......
    ..............KGGBBBBBEEBBK.....
    ..............KGGBBBBBNHBBPK....
    ..............KGGBBOOBBBBPPPK...
    ..............KGGBOOOBBBBPNPK...
    ...............KGGBBBBBBBKKPK...
    ...............KGGGBBBBBBK.K....
    ..............KGWWGGGGGGGGK.....
    .............KGWWWWGGGGGGGK.....
    .............KDWWWWWKGGGGGK.....
    ............KDDDWWWWKGGGGGK.....
    ............KDDDDDWWKGGGGGK.....
    ...........KDDDDDDDKGGGGGK......
    ..........KDDDDDDDKGGGGGK.......
    .........KDDDKKKKKGGGGKK........
    .......KKDDDKK...KFKKFK.........
    .....KKDDDKK....KFFKFFK.........
    ......KKKK.......KK.KK..........
    ................................
""")

STAND_B = art("""
    ................................
    ................KK..............
    ...............KBBKK............
    ................KKYBK...........
    ..................KYBK..........
    ...................KYBK.........
    ...................KYBBK........
    .................KKKYBBBK.......
    ...............KKGGBBBBBK.......
    ..............KGGBBBBBBBBK......
    ..............KGGBBBBBEEBBK.....
    ..............KGGBBBBBNHBBPK....
    ..............KGGBBOOBBBBPPPK...
    ..............KGGBOOOBBBBPNPK...
    ...............KGGBBBBBBBKKPK...
    ..............KGWWGGGGGGGGKK....
    .............KGWWWWGGGGGGGK.....
    .............KDWWWWWKGGGGGK.....
    ............KDDDWWWWKGGGGGK.....
    ............KDDDDDWWKGGGGGK.....
    ...........KDDDDDDDKGGGGGK......
    ..........KDDDDDDDKGGGGGK.......
    .........KDDDKKKKKGGGGKK........
    .......KKDDDKK...KFKKFK.........
    .....KKDDDKK....KFFKFFK.........
    ......KKKK.......KK.KK..........
    ................................
""")

FLY_0 = art("""
    ................................
    ................................
    ..KK............................
    ..KDKK......KK..................
    ...KDDKK...KBBK.................
    ...KDDDDKK.KYBBKK...............
    ....KDDDDDKKKYYBBKKK............
    ....KDDDDDDDKKKYYBBBKKK.........
    .....KDDDDDDDK.KKYYBBBBKK.......
    .....KDDDDDDWWK..KKBBBBBBK......
    ......KDDDDWWWWKKKGGBBBBBK......
    ......KDDDWWWWWKGGBBBBBBBBK.....
    .....KKKWWWWWWWKGGBBBBBEEBBK....
    .......KKKKWWWWKGGBBBBBNHBBPK...
    .......KGGGKKKKKGGBBOOBBBBPPPK..
    ...KKKKDGGGGGGGGGGBOOOBBBBPNPK..
    .KKDDDDDDGGGGGGGGGGBBBBBBBKKPK..
    KDDDDDDDDKGGGGGGGGGGGGGGGK..K...
    .KKKDDDDDDKGGGGGGGGGGGGGK.......
    ....KKKKDDKGGGGGGGGGGGGK........
    ........KKKKGGGGGGGGGKK.........
    ............KKKKKKKKK...........
    ................................
    ................................
    ................................
    ................................
    ................................
""")

FLY_1 = art("""
    ................................
    ................................
    ............KK..................
    ...........KBBK.................
    ...........KYBBKK...............
    ............KYYBBKKK............
    .............KKYYBBBKKK.........
    ...............KKYYBBBBKK.......
    .................KKBBBBBBK......
    .........KKKKKKKKKGGBBBBBK......
    ......KKKDDWWWWKGGBBBBBBBBK.....
    ....KKDDDDDDWWWKGGBBBBBEEBBK....
    ..KKDDDDDDDDDWWKGGBBBBBNHBBPK...
    .KDDDDDDDDDDDDWKGGBBOOBBBBPPPK..
    ..KKKKKKKKKKKKKKGGBOOOBBBBPNPK..
    .KKDDDDDDGGGGGGGGGGBBBBBBBKKPK..
    KDDDDDDDDKGGGGGGGGGGGGGGGK..K...
    .KKKDDDDDDKGGGGGGGGGGGGGK.......
    ....KKKKDDKGGGGGGGGGGGGK........
    ........KKKKGGGGGGGGGKK.........
    ............KKKKKKKKK...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
""")

FLY_2 = art("""
    ................................
    ............KK..................
    ...........KBBK.................
    ...........KYBBKK...............
    ............KYYBBKKK............
    .............KKYYBBBKKK.........
    ...............KKYYBBBBKK.......
    .................KKBBBBBBK......
    ............KKKKKKGGBBBBBK......
    ..........KKGGGGGGBBBBBBBBK.....
    .........KGGGGGGGGBBBBBEEBBK....
    .......KKKKKKKKKGGBBBBBNHBBPK...
    ......KDWWWWWWWKGGBBOOBBBBPPPK..
    ...KKKKDDWWWWWWKGGBOOOBBBBPNPK..
    .KKDDKDDDDWWWWWKGGGBBBBBBBKKPK..
    KDDDDKDDDDDWWWKGGGGGGGGGGK..K...
    .KKKKDDDDDDDKKGGGGGGGGGGK.......
    ....KDDDDDDKGGGGGGGGGGGK........
    ...KDDDDDDKKGGGGGGGGGKK.........
    ...KDDDDDK..KKKKKKKKK...........
    ..KDDDDK........................
    ..KDDDK.........................
    ...KKK..........................
    ................................
    ................................
    ................................
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ...........KK...................
    ..........KBBKKK................
    ...........KYYBBKKKK............
    ............KKYBBBBBKKKK........
    ..............KYYBBBBBBBK.......
    ...............KKGGBBBBBK.......
    ..............KGGBBBBBBBBK......
    ..............KGGBBBBBEEBBK.....
    ..............KGGBBBBBNHBBPK....
    ..............KGGBBOOBBBBPPPK...
    ..............KGGBOOOBBBBPNPK...
    ...............KGGBBBBBBBKKPK...
    ..............KGGGGBBBBBBK.K....
    .............KGWWGGGGGGGGGK.....
    ............KGWWWWWGGGGGGGGK....
    ............KDWWWWWWKGGGGGGGK...
    ...........KDDDWWWWWKGGGGGGGK...
    ...........KDDDDDWWKGGGGGGGGK...
    ..........KDDDDDDDKGGGGGGGGGK...
    ........KKDDDDDDDKGGGGGGGGGK....
    ......KKDDDDDKKKKGGGFFGFFGKK....
    .....KKKKKKKK...KKKKKKKKKK......
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ...........KK...................
    ..........KBBKKK................
    ...........KYYBBKKKK............
    ............KKYBBBBBKKKK........
    ..............KYYBBBBBBBK.......
    ...............KKGGBBBBBK.......
    ..............KGGBBBBBBBBK......
    ..............KGGBBBBBEEBBK.....
    ..............KGGBBBBBNHBBPK....
    ..............KGGBBOOBBBBPPPK...
    ..............KGGBOOOBBBBPNPK...
    ...............KGGBBBBBBBKKPK...
    ...............KGGGBBBBBBBKK....
    .............KKGGGGBBBBBBBK.....
    ............KGWWWGGGGGGGGGK.....
    ...........KGWWWWWGGGGGGGGGK....
    ...........KDWWWWWWKGGGGGGGGK...
    ..........KDDDWWWWWKGGGGGGGGK...
    ..........KDDDDDWWKGGGGGGGGGK...
    .........KDDDDDDDKGGGGGGGGGGK...
    .......KKDDDDDDDKGGGGGGGGGGK....
    .....KKDDDDDKKKKKGGFFGFFGGKK....
    ....KKKKKKKK....KKKKKKKKKKK.....
    ................................
""")

CARRIED_A = art("""
    .....................KK.........
    ....................KBBK........
    ...................KYBK.........
    ...................KYBK.........
    ...................KYBBK........
    .......KK.........KKYBBBK.......
    .......KDKK......KKKYBBBK.......
    ........KDDKK..KKGGBBBBBK.......
    ........KDDDDKKGGBBBBBBBBK......
    .........KDDDDKGGBBBBBEEBBK.....
    .........KDDDDKGGBBBBBNHBBPK....
    ..........KDDWKGGBBOOBBBBPPPK...
    ..........KDWWKGGBOOOBBBBPNPK...
    ...........KWWWKGGBBBBBBBKKPK...
    ...........KWWWWWKGBBBBBBK.K....
    ............KKWWWKGGGGGGGGK.....
    .............KKKKGGGGGGGGGK.....
    .............KGGGGGGGGGGGGK.....
    ............KGGGGGGGGGGGGGK.....
    ............KDGGGGGGGGGGGGK.....
    ...........KDDDGGGGGGGGGGK......
    ..........KDDDDDGGGGGGGGK.......
    .........KDDDDDKKGGGGGKK........
    ........KDDDDDK.KFKKFK..........
    ........KDDDDK..KFKKFK..........
    .........KKKK....K..K...........
    ................................
""")

CARRIED_B = art("""
    .....................KK.........
    ....................KBBK........
    ...................KYBK.........
    ...................KYBK.........
    ...................KYBBK........
    ..................KKYBBBK.......
    .................KKKYBBBK.......
    ...............KKGGBBBBBK.......
    ..............KGGBBBBBBBBK......
    ..............KGGBBBBBEEBBK.....
    ..............KGGBBBBBNHBBPK....
    ..............KGGBBOOBBBBPPPK...
    ..............KGGBOOOBBBBPNPK...
    ...............KGGBBBBBBBKKPK...
    ..............KKKKKBBBBBBK.K....
    .............KWWWWWKGGGGGGK.....
    ............KWWWWWWKGGGGGGK.....
    ..........KKDWWWWWKGGGGGGGK.....
    ........KKDDDDWWWKGGGGGGGGK.....
    ......KKDDDDDDDKKGGGGGGGGGK.....
    ....KKDDDDDDDKKGGGGGGGGGGK......
    ...KDDDDDDKKDDDDGGGGGGGGK.......
    ...KDDDKKKDDDDDKKGGGGGKK........
    ....KKK.KDDDDDK.KFKKFK..........
    ........KDDDDK..KFKKFK..........
    .........KKKK....K..K...........
    ................................
""")

COCKATIEL = Species(
    key="cockatiel",
    label=QT_TRANSLATE_NOOP("Species", "Cockatiel"),
    palette={
        "K": "#2a2730",  # outline
        "B": "#f7d64a",  # yellow face and crest; the eye sits in it, so a blink closes it
        "Y": "#dcae2c",  # darker yellow: back and underside of the crest
        "O": "#f07a34",  # orange cheek patch
        "G": "#8f8e96",  # gray feathers
        "D": "#64636d",  # dark gray flight feathers and tail
        "W": "#f4f2ec",  # white wing patch
        "P": "#c2bbbb",  # pale gray beak
        "N": "#1c1a20",  # pupil, beak line
        EYE: "#1c1a20",
        EYE_SHINE: "#ffffff",
        "F": "#c9a3a0",  # pinkish-gray feet
    },
    animations={
        # Bobbing its head now and then.
        Activity.STANDING: Animation((STAND_A, STAND_A, STAND_A, STAND_B, STAND_A, STAND_B), fps=3),
        Activity.WALKING: Animation((FLY_0, FLY_1, FLY_2, FLY_1), fps=10),  # it flies around
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # fluffed up, crest down, breathing
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=8),  # flapping, crest up in alarm
    },
    gait=Gait(speed=80, max_slope=1.0, distance=(120, 420)),
    locomotion=Locomotion.FLY,
)
