"""The dog: a beagle-like puppy with a red collar."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ....................KKKKKK......
    ...................KBBBBBBK.....
    ..................KDDBBBBBBK....
    ..KK.............KDDDBBBEEBBK...
    .KWWK............KDDDBBBNHBBK...
    .KWWK............KDDDDBBBBBBKKK.
    ..KBBK...........KDDDDBBBWWWWNNK
    ..KBBK...........KDDDBBBWWWWWWNK
    ..KBBBK..KKKKKKKKKDDDBBBWWWWWWWK
    ...KBBBKKDDDDDDDDKKRRRBBBWWWNNK.
    ....KBBKDDDDDDDDDDBBWWRKKKKPPK..
    .....KBBDDDDDDDDDDBWWWYWK..KPK..
    ....KBBBBBBDDDDBBBBWWWWWK...K...
    ....KBBBBBBBBBBBBBBWWWWWK.......
    ....KBBBBBBBBBBBBBBBWWWK........
    .....KBBBWWWWWWWWWWBBWK.........
    ......KBBWWWWWWWWBBBDDK.........
    ......KBBKDBBBBBBBBKDDK.........
    ......KBBKDDKKKKKBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KWWKWWK...KWWKWWK.........
    .......KK.KK.....KK.KK..........
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ................................
    ....................KKKKKK......
    ...................KBBBBBBK.....
    ..................KDDBBBBBBK....
    .................KDDDBBBEEBBK...
    .................KDDDBBBNHBBK...
    .................KDDDDBBBBBBKKK.
    KK...............KDDDDBBBWWWWNNK
    WWKKK............KDDDBBBWWWWWWNK
    WWBBBKK..KKKKKKKKKDDDBBBWWWWWWWK
    KKBBBBBKKDDDDDDDDKKRRRBBBWWWNNK.
    ..KKBBBKDDDDDDDDDDBBWWRKKKKPPK..
    ....KKBBDDDDDDDDDDBWWWYWK..KPK..
    ....KBBBBBBDDDDBBBBWWWWWK...K...
    ....KBBBBBBBBBBBBBBWWWWWK.......
    ....KBBBBBBBBBBBBBBBWWWK........
    .....KBBBWWWWWWWWWWBBWK.........
    ......KBBWWWWWWWWBBBDDK.........
    ......KBBKDBBBBBBBBKDDK.........
    ......KBBKDDKKKKKBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KWWKWWK...KWWKWWK.........
    .......KK.KK.....KK.KK..........
    ................................
""")

WALK_0 = art("""
    ................................
    ................................
    ................................
    ....................KKKKKK......
    ...................KBBBBBBK.....
    ..................KDDBBBBBBK....
    ..KK.............KDDDBBBEEBBK...
    .KWWK............KDDDBBBNHBBK...
    .KWWK............KDDDDBBBBBBKKK.
    ..KBBK...........KDDDDBBBWWWWNNK
    ..KBBK...........KDDDBBBWWWWWWNK
    ..KBBBK..KKKKKKKKKDDDBBBWWWWWWWK
    ...KBBBKKDDDDDDDDKKRRRBBBWWWNNK.
    ....KBBKDDDDDDDDDDBBWWRKKKKPPK..
    .....KBBDDDDDDDDDDBWWWYWK..KPK..
    ....KBBBBBBDDDDBBBBWWWWWK...K...
    ....KBBBBBBBBBBBBBBWWWWWK.......
    ....KBBBBBBBBBBBBBBBWWWK........
    .....KBBBWWWWWWWWWWBBWK.........
    ......KBBWWWWWWWWBBBDDK.........
    ......KBBKDBBBBBBBBKDDK.........
    ......KBBKKDDKKKKBBDDK..........
    .....KBBK.KDDK...KBBDK..........
    .....KBBK.KDDK...KBBDK..........
    .....KWWK.KWWK...KWWWK..........
    ......KK...KK.....KKK...........
    ................................
""")

WALK_1 = art("""
    ................................
    ................................
    ....................KKKKKK......
    ...................KBBBBBBK.....
    ..................KDDBBBBBBK....
    ..KK.............KDDDBBBEEBBK...
    .KWWK............KDDDBBBNHBBK...
    .KWWK............KDDDDBBBBBBKKK.
    ..KBBK...........KDDDDBBBWWWWNNK
    ..KBBK...........KDDDBBBWWWWWWNK
    ..KBBBK..KKKKKKKKKDDDBBBWWWWWWWK
    ...KBBBKKDDDDDDDDKKRRRBBBWWWNNK.
    ....KBBKDDDDDDDDDDBBWWRKKKKPPK..
    .....KBBDDDDDDDDDDBWWWYWK..KPK..
    ....KBBBBBBDDDDBBBBWWWWWK...K...
    ....KBBBBBBBBBBBBBBWWWWWK.......
    ....KBBBBBBBBBBBBBBBWWWK........
    .....KBBBWWWWWWWWWWBBWK.........
    ......KBBWWWWWWWWBBBDDK.........
    ......KBBKDBBBBBBBBKDDK.........
    ......KBBKDDKKKKKBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBKWWK...KWWKDDK.........
    ......KWWKKK.....KKKWWK.........
    .......KK...........KK..........
    ................................
""")

WALK_2 = art("""
    ................................
    ................................
    ................................
    ....................KKKKKK......
    ...................KBBBBBBK.....
    ..................KDDBBBBBBK....
    .................KDDDBBBEEBBK...
    .................KDDDBBBNHBBK...
    .................KDDDDBBBBBBKKK.
    KK...............KDDDDBBBWWWWNNK
    WWKKK............KDDDBBBWWWWWWNK
    WWBBBKK..KKKKKKKKKDDDBBBWWWWWWWK
    KKBBBBBKKDDDDDDDDKKRRRBBBWWWNNK.
    ..KKBBBKDDDDDDDDDDBBWWRKKKKPPK..
    ....KKBBDDDDDDDDDDBWWWYWK..KPK..
    ....KBBBBBBDDDDBBBBWWWWWK...K...
    ....KBBBBBBBBBBBBBBWWWWWK.......
    ....KBBBBBBBBBBBBBBBWWWK........
    .....KBBBWWWWWWWWWWBBWK.........
    ......KBBWWWWWWWWBBBDDK.........
    ......KBBKDBBBBBBBBKDDK.........
    ......KBBDDKKKKKKBBKKDDK........
    .......KBBDK...KBBK.KDDK........
    .......KBBDK...KBBK.KDDK........
    .......KWWWK...KWWK.KWWK........
    ........KKK.....KK...KK.........
    ................................
""")

WALK_3 = art("""
    ................................
    ................................
    ....................KKKKKK......
    ...................KBBBBBBK.....
    ..................KDDBBBBBBK....
    .................KDDDBBBEEBBK...
    .................KDDDBBBNHBBK...
    .................KDDDDBBBBBBKKK.
    KK...............KDDDDBBBWWWWNNK
    WWKKK............KDDDBBBWWWWWWNK
    WWBBBKK..KKKKKKKKKDDDBBBWWWWWWWK
    KKBBBBBKKDDDDDDDDKKRRRBBBWWWNNK.
    ..KKBBBKDDDDDDDDDDBBWWRKKKKPPK..
    ....KKBBDDDDDDDDDDBWWWYWK..KPK..
    ....KBBBBBBDDDDBBBBWWWWWK...K...
    ....KBBBBBBBBBBBBBBWWWWWK.......
    ....KBBBBBBBBBBBBBBBWWWK........
    .....KBBBWWWWWWWWWWBBWK.........
    ......KBBWWWWWWWWBBBDDK.........
    ......KBBKDBBBBBBBBKDDK.........
    ......KBBKDDKKKKKBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KWWKDDK...KBBKWWK.........
    .......KKKWWK...KWWKKK..........
    ..........KK.....KK.............
    ................................
""")

SIT_A = art("""
    ................KKKKKK..........
    ...............KBBBBBBK.........
    ..............KDDBBBBBBK........
    .............KDDDBBBEEBBK.......
    .............KDDDBBBNHBBK.......
    .............KDDDDBBBBBBKKK.....
    .............KDDDDBBBWWWWNNK....
    .............KDDDBBBWWWWWWNK....
    .............KDDDBBBWWWWWWWK....
    ............KKBRRRBBBWWWNNK.....
    ...........KDDBBBBRKKKKPPK......
    ..........KDDDDBBBYWWK.KPK......
    ..........KDDDDBBBWWWWK.K.......
    ..........KDDDDBBWWWWWK.........
    ..........KDDDDBBWWWWWK.........
    .........KBDDDDBBWWWWWK.........
    .........KBDDDDBBWWWBBK.........
    .........KBBBBBBBBWWBBK.........
    ........KBBBBBBBBBWWBBK.........
    .......KBBBBBBBBBBBBBBK.........
    .......KBBBBBBBBBBBBBBK.........
    .......KBBBBBBBBBBBDBBK.........
    ..KKKKKKBBBBBBBBBBDDBBK.........
    .KWWBBBBBBBBBBBBBKDDBBK.........
    .KWWBBBBKKKKBBBWWWWWWWK.........
    ..KKKKKK....KKKKKKKKKK..........
    ................................
""")

SIT_B = art("""
    ................KKKKKK..........
    ...............KBBBBBBK.........
    ..............KDDBBBBBBK........
    .............KDDDBBBEEBBK.......
    .............KDDDBBBNHBBK.......
    .............KDDDDBBBBBBKKK.....
    .............KDDDDBBBWWWWNNK....
    .............KDDDBBBWWWWWWNK....
    .............KDDDBBBWWWWWWWK....
    ............KKBRRRBBBWWWNNK.....
    ...........KDDBBBBRKKKKPPK......
    ..........KDDDDBBBYWWK.KPK......
    ..........KDDDDBBBWWWWK.K.......
    ..........KDDDDBBWWWWWK.........
    ..........KDDDDBBWWWWWK.........
    .........KBDDDDBBWWWWWK.........
    .........KBDDDDBBWWWBBK.........
    .........KBBBBBBBBWWBBK.........
    ........KBBBBBBBBBWWBBK.........
    ..KK...KBBBBBBBBBBBBBBK.........
    .KWWKK.KBBBBBBBBBBBBBBK.........
    .KWWBBKKBBBBBBBBBBBDBBK.........
    ..KKBBBBBBBBBBBBBBDDBBK.........
    ....KKBBBBBBBBBBBKDDBBK.........
    ......KKKKKKBBBWWWWWWWK.........
    ............KKKKKKKKKK..........
    ................................
""")

CARRIED_A = art("""
    ................................
    ...................KK...........
    ..................KDDK..........
    ..................KDDDKKKK......
    .................KDDDDBBBBK.....
    .................KDDDDBBBBBK....
    .................KBDDDBBEEBBK...
    .................KBDDBBBNHBBK...
    .................KBBBBBBBBBBKKK.
    .................KBBBBBBBWWWWNNK
    .................KBBBBBBWWWWWWNK
    .........KKKKKKKK.KBBBBBWWWWWWWK
    .....KK.KDDDDDDDDKKRRRBBBWWWNNK.
    ....KBBKDDDDDDDDDDBBWWRKKKKKNK..
    ...KBBBBDDDDDDDDDDBWWWYWK...K...
    ..KBBBBBBBBDDDDBBBBWWWWWK.......
    ..KBBBBBBBBBBBBBBBBWWWWWK.......
    .KWWKBBBBBBBBBBBBBBBWWWK........
    .KWWKKBBBWWWWWWWWWWBBWK.........
    ..KK.KBBBWWWWWWWWWBBDK..........
    .....KBBKKKBBBBBBKBBDK..........
    .....KBBK.KDDKKKKKBBDK..........
    .....KBBK.KDDK...KBBDK..........
    .....KBBK.KDDK...KBBDK..........
    .....KBBK.KDDK...KBBDK..........
    .....KWWK.KWWK...KWWWK..........
    ......KK...KK.....KKK...........
""")

CARRIED_B = art("""
    ................................
    ...................KK...........
    ..................KDDK..........
    ..................KDDDKKKK......
    .................KDDDDBBBBK.....
    .................KDDDDBBBBBK....
    .................KBDDDBBEEBBK...
    .................KBDDBBBNHBBK...
    .................KBBBBBBBBBBKKK.
    .................KBBBBBBBWWWWNNK
    .................KBBBBBBWWWWWWNK
    .........KKKKKKKK.KBBBBBWWWWWWWK
    .....KK.KDDDDDDDDKKRRRBBBWWWNNK.
    ....KBBKDDDDDDDDDDBBWWRKKKKKNK..
    ...KBBBBDDDDDDDDDDBWWWYWK...K...
    ..KBBBBBBBBDDDDBBBBWWWWWK.......
    ..KBBBBBBBBBBBBBBBBWWWWWK.......
    .KWWKBBBBBBBBBBBBBBBWWWK........
    .KWWKKBBBWWWWWWWWWWBBWDK........
    ..KK..KKBBWWWWWWBBWBKDDK........
    .......KBBDBBBBBBBKKKDDK........
    .......KBBDKKKKKBBK.KDDK........
    .......KBBDK...KBBK.KDDK........
    .......KBBDK...KBBK.KDDK........
    .......KBBDK...KBBK.KDDK........
    .......KWWWK...KWWK.KWWK........
    ........KKK.....KK...KK.........
""")

DOG = Species(
    key="dog",
    label=QT_TRANSLATE_NOOP("Species", "Dog"),
    palette={
        "K": "#3b2518",  # outline
        "B": "#dc9a57",  # fur
        "D": "#a4622f",  # dark fur: ear, back patch, far legs
        "W": "#f7ead5",  # cream: muzzle, chest, belly, paws, tail tip
        "N": "#221612",  # nose, mouth, pupil
        EYE: "#221612",
        EYE_SHINE: "#ffffff",
        "P": "#e56b7a",  # tongue
        "R": "#d33c3c",  # collar
        "Y": "#f5c542",  # collar tag
    },
    animations={
        Activity.STANDING: Animation((STAND_A, STAND_B), fps=3),  # wagging its tail
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_3), fps=8),
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1.5),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),
    },
    gait=Gait(speed=45, max_slope=0.4, distance=(80, 320)),
)
