"""The fish: a betta with a blue body and long red fins."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

FLOAT_A = art("""
    ................................
    ................................
    ...........KKKK.................
    .....KK...KRRRRKKKK.............
    ....KRSK..KSRRRRSRRKK...........
    ...KRRRSK..KSRRRSSRRSK..........
    ...KRRRRSK..KSRRRSRRSK..........
    ..KRRRRRRSK.KRSRRSSRRK..........
    ..KSSRRRRSSK.KRSRRSRKKKKK.......
    ..KRRSSRRFSRKSRRSKKKDDDDDKK.....
    .KRRRRRSAAFSRSSKKDDDDDDDDDDK....
    .KRRRRRRFAAASKKBBBBBBBBDBEEBBK..
    .KRRRRRRFFFAKBBBBBBBBBBDBNHBBBK.
    .KSSSSSSAAAAKBBBBBBBBBBDBBBBBNK.
    .KRRRRRRFFAASKLLLLLLLLLDLLLLK...
    .KRRRRRRSAFSRSKKLLLLLLLDLLKK....
    ..KRRRSSSRSSKSRRKKKKKKKKKRK.....
    ..KRSSSRRRSK.KRSRRSRRSK.KRK.....
    ..KSSRRRRSK..KSSRSSRSSKKRRK.....
    ...KRRRRSK..KRSRRSRRSK.KRK......
    ...KRRRRK...KSRRSSRSK..KK.......
    ....KRRK...KSSRRSKKK............
    .....KK....KSKKKK...............
    ...........KK...................
    ................................
    ................................
    ................................
""")

FLOAT_B = art("""
    ................................
    ................................
    ...........KKKKKK...............
    .....KK....KRRRSSKK.............
    ....KRRK...KSRRRSRRKK...........
    ....KRRRK...KSRRRSRRSK..........
    ....KRRRSK..KRSRRSRRSK..........
    ...KRRRRRSK..KSSRRSRRSK.........
    ...KSSRRRRSK.KRSSRSSKKKKK.......
    ...KRRSSRFSSK.KRSKKKDDDDDKK.....
    ..KRRRRSAAFSRKSKKDDDDDDDDDDK....
    ..KRRRRRFFAASKKBBBBBBBBDBEEBBK..
    ..KRRRRRFFFAKBBBBBBBBBBDBNHBBBK.
    ..KSSSSSAAAAKBBBBBBBBBBDBBBBBNK.
    ..KRRRRRFFAASKLLLLLLLLLDLLLLK...
    ..KRRRRRRAASRKKKLLLLLLLDLLKK....
    ...KRRRSSRRSK.KRKKKKKKKKKRK.....
    ...KRSSRRRSK.KRSSRSRRSK..KRK....
    ...KSSRRRSK..KRSRRSRRSK..KRRK...
    ....KRRRRK...KSSRSRRSK....KRK...
    ....KRRRK...KRSRRSRSK.....KK....
    ....KRRK....KSRRSRKK............
    .....KK....KSSRKKK..............
    ...........KKKK.................
    ................................
    ................................
    ................................
""")

SWIM_1 = art("""
    ................................
    ................................
    .......KK..KKKKKK...............
    ......KRK..KSRRRSKK.............
    ......KRRK.KSRRRSRRKK...........
    .....KRRRK..KSRRRSRRSK..........
    ....KSRRRRK.KRSRRSRRSK..........
    ....KSSRRRSK.KSSRRSRRSK.........
    ....KRSSRRRSKSRSSRSSKKKKK.......
    ...KRRRRSAFSRSSRSKKKDDDDDKK.....
    ...KRRRRFAAFSRSKKDDDDDDDDDDK....
    ...KRRRRFFFAAKKBBBBBBBBDBEEBBK..
    ...KSSSSAAAAKBBBBBBBBBBDBNHBBBK.
    ...KRRRRFFFAKBBBBBBBBBBDBBBBBNK.
    ...KRRRRFAAASKLLLLLLLLLDLLLLK...
    ...KRRRSSARSRSKKLLLLLLLDLLKK....
    ...KRSSSRRSKKSRRKKKKKKKKKRK.....
    ...KSSRRRSK..KRSRRSRRSK..KRK....
    ...KRRRRRK..KRSRRSRRSSK..KRRK...
    ....KRRRK...KSSRSSRRSK....KRK...
    ....KRRK...KSSRRSRRSK.....KK....
    .....KK...KSSRRSKKKK............
    ..........KKKKKK................
    ................................
    ................................
    ................................
    ................................
""")

SWIM_2 = art("""
    ................................
    ................................
    ...........KKKKKKK..............
    .......KK..KSRRRSRKK............
    ......KRK...KSRRSSRRK...........
    ......KRRK..KSSRRSRRSK..........
    ......KRRSK..KSRRSSRSK..........
    .....KRRRRK..KRSRRSRRSK.........
    .....KSSRRSK.KRSSRSSKKKKK.......
    .....KRRSFRSK.KRSKKKDDDDDKK.....
    .....KRRFAASSKSKKDDDDDDDDDDK....
    .....KRRFFFASKKBBBBBBBBDBEEBBK..
    .....KRRFFFFKBBBBBBBBBBDBNHBBBK.
    .....KSSAAAAKBBBBBBBBBBDBBBBBNK.
    .....KRRFFFASKLLLLLLLLLDLLLLK...
    .....KRRRFARSKKKLLLLLLLDLLKK....
    .....KRRSSRSK.KRKKKKKKKKKRK.....
    .....KRSSRRK..KRSRSSRSK..KRK....
    .....KSSRRK..KRSRRSRSSK..KRRK...
    ......KRRRK..KRSRSSRSK....KRK...
    ......KRRK...KSRRSRRK.....KK....
    ......KRK...KRSRSSKK............
    .......KK...KSRRKK..............
    ............KSKK................
    ............KK..................
    ................................
    ................................
""")

SWIM_3 = art("""
    ................................
    ................................
    ................................
    ..........KKKKKKKK..............
    .....KK...KRRRRSRRKK............
    ....KRSK..KSSRRRSRRSK...........
    ....KRRSK..KSSRRSSRRSK..........
    ....KRRRSK..KSSRRSRRRK..........
    ...KRRRRRSK.KRSSRRSRKKKKK.......
    ...KSSSRRRSKSSRSSKKKDDDDDKK.....
    ...KRRSSAFRSRSSKKDDDDDDDDDDK....
    ...KRRRRFAAASKKBBBBBBBBDBEEBBK..
    ...KRRRRFFFAKBBBBBBBBBBDBNHBBBK.
    ...KRRRRAAAAKBBBBBBBBBBDBBBBBNK.
    ...KSSSSFFFAAKLLLLLLLLLDLLLLK...
    ...KRRRRRFAASRKKLLLLLLLDLLKK....
    ....KRRRRSFSSSSRKKKKKKKKKRK.....
    ....KRRSSRRSKSRSSRSSRSK..KRK....
    ....KRSSRRSK.KRSRRSRRSK..KRRK...
    .....KSRRRK..KSSRSRRSK....KRK...
    .....KRRRK..KRSRRSRSK.....KK....
    ......KRRK..KSRRSRKK............
    ......KRK...KSRRKK..............
    .......KK...KKKK................
    ................................
    ................................
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKK....................
    ........KRRK....................
    .......KRRRRK...................
    ......KSSRRRK...................
    ......KRSSSSSKKKKKK.............
    .....KRRRSRSSRSRRSSKK...........
    ....KRRRRSARSSRSRRSRKKKKK.......
    ....KSRRRFAASSSRSKKKDDDDDKK.....
    ....KSSSAFFARSSKKDDDDDDDDDDK....
    ...KRRRRAAAFAKKBBBBBBBBDBEEBBK..
    ...KRRRRFFFAKBBBBBBBBBBDBNHBBBK.
    ...KRRRRAAAAKBBBBBBBBBBDBBBBBNK.
    ...KSSSSAFRSSKLLLLLLLLLDLLLLK...
    ...KRRRRRSSKSSKKLLLLLLLDLLKK....
    ...KRRRRKKK.KRRRKKKKKKKKKRK.....
    ...KKKKK..KKKKKKKKKK....KKK.....
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ........KKK.....................
    .......KRRK.....................
    ......KRRRRK....................
    ......KSRRRK....................
    .....KRSSSSSKKKKKKK.............
    ....KRRRSRSSRSSRRSSKK...........
    ....KRRRRSFRSSRSRRSRKKKKK.......
    ....KRRRRFAFSSSSSKKKDDDDDKK.....
    ...KSSSRFFFASRSKKDDDDDDDDDDK....
    ...KRRRSAAAAAKKBBBBBBBBDBEEBBK..
    ...KRRRRFFAAKBBBBBBBBBBDBNHBBBK.
    ...KRRRRFAAAKBBBBBBBBBBDBBBBBNK.
    ..KRRSSSAAFSSKLLLLLLLLLDLLLLK...
    ..KSSSRRRRSSSSKKLLLLLLLDLLKK....
    ..KRRRRRRKSSSRRRKKKKKKKKKRK.....
    ...KKKKKK.KKKKKKKKKK....KKK.....
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ................................
    .........KKKKKKKK...............
    ........KRRRRRSRRKK.............
    .........KSRRRSSRRSK............
    ..KK......KSRRRSSRRSK...........
    ..KSKK....KRSRRRSRRSK...........
    .KRRRSKK...KRSRRRSRKKKKK........
    .KRRRRSSKKK.KRSSKKKDDDDDKK......
    .KRRRRRRSSRKSSKKDDDDDDDDDDK.....
    .KSRRRRFFASRKKBBBBBBBBDBEEBBK...
    .KSSSSSAAAAKBBBBBBBBBBDBNHBBBK..
    .KRRRRRFFFAKBBBBBBBBBBDBBBBBNK..
    ..KRRRRFAAAAKLLLLLLLLLDLLLLK....
    ..KRRRSSAFAASKKLLLLLLLDLLKK.....
    ..KRSSRRRAASSRRKKKKKKKKSSSK.....
    ...KRRRRRSRSRRSRRSRRSK.KSKK.....
    ...KRRRRSRRSRSRRSRRSSK..KRRK....
    ....KRRSSRSRSRRSSRSSK....KRK....
    ....KRRSRRSSRRSSRRKK.....KK.....
    .....KSRRSSSRRKKKK..............
    ......KRSSSKKK..................
    .......KKRK.....................
    .........K......................
    ................................
    ................................
""")

CARRIED_B = art("""
    ................................
    ..........KK....................
    .........KRK....................
    ........KRRSKKKKKKK.............
    .......KRRSRRRRRSRRKK...........
    ......KRSRRSSRRRSSRRSK..........
    .....KRRSSRRSSRRRSSRRSK.........
    .....KRRRSSRSRSRRRSRRSK.........
    ....KRRRRRSFRSRSRRRSRKKKKK......
    ....KSRRRRFAFSSRSSKKKDDDDDKK....
    ...KRRSSSFFFASRSKKDDDDDDDDDDK...
    ...KRRRRRAAAAAKKBBBBBBBBDBEEBBK.
    ...KRRRRRFFFAKBBBBBBBBBBDBNHBBBK
    ...KRRRRRAAAAKBBBBBBBBBBDBBBBBNK
    ...KSSSSSFFRSSKLLLLLLLLLDLLLLK..
    ...KRRRRRRSSKKSKKLLLLLLLDLLKK...
    ...KRRRRRKKK..KRRKKKKKKKKSSSK...
    ...KRRRKK....KRRSRRSRRSK.KSKK...
    ...KRKK......KRSRRSRRSSK..KRRK..
    ....K.......KRSRRSSRSSK....KRK..
    ............KSRRSSRRKK.....KK...
    ...........KSSRRKKKK............
    ...........KKKKK................
    ................................
    ................................
    ................................
    ................................
""")

FISH = Species(
    key="fish",
    label="Fish",
    palette={
        "K": "#191a3f",  # outline
        "B": "#2f5fd0",  # blue body
        "D": "#22419e",  # back, edge of the gill cover
        "L": "#4f84e0",  # belly
        "F": "#4a6ae0",  # blue at the base of the tail
        "A": "#2f49b8",  # rays at the base of the tail
        "R": "#e8506a",  # red fins
        "S": "#b8385a",  # rays and folds in the fins, beard
        "N": "#0d0d1f",  # pupil, mouth
        EYE: "#0d0d1f",
        EYE_SHINE: "#ffffff",
    },
    animations={
        # Like the sea turtle, it floats between swims and only touches the ground when sitting.
        Activity.STANDING: Animation((FLOAT_A, FLOAT_B), fps=1.5),  # fins waving
        Activity.WALKING: Animation((FLOAT_A, SWIM_1, SWIM_2, SWIM_3), fps=6),  # the tail beats
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # resting on the bottom
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=8),  # flaring, flicking its tail
    },
    gait=Gait(speed=40, max_slope=0.8, distance=(80, 300)),
    locomotion=Locomotion.SWIM,
)
