"""The fox: a red fox with black stockings and a big bushy tail tipped in white."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .KKK.............KDDBBBBBBBBBK..
    KWWWK............KDBBBBBEEBBBBK.
    KWWWWK...........KDBBBBBEEBBBBBK
    KWWWBBK..........KBBBBBBNHBBBBNN
    KWWBBBBKK........KBBWWWWWWWWWKK.
    KBBBBBBBBKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWWK......
    .KDDBBBBBBBBBBBBBBBBWWWWK.......
    ..KDDDBBBBBBBBBBBBBBBWWWK.......
    ...KKDDDDKBBBBBBBBBBBBBWK.......
    .....KKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    .........KK.KK.....KK.KK........
    ................................
""")

STAND_B = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .................KDDBBBBBBBBBK..
    .................KDBBBBBEEBBBBK.
    .KKK.............KDBBBBBEEBBBBBK
    KWWWKK...........KBBBBBBNHBBBBNN
    KWWWWBKK.........KBBWWWWWWWWWKK.
    KWWBBBBBKKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KBBBBBBBBBBBBBBBBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWK.......
    .KDDDBBBBBBBBBBBBBBBBWWWK.......
    ..KKDDDDDKBBBBBBBBBBBBBWK.......
    ....KKKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    .........KK.KK.....KK.KK........
    ................................
""")

STAND_C = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSSSK.....
    ..................KSDDKSSBBK....
    ..................KDDBBBBBBBK...
    .KKK.............KDDBBBBBBBBBK..
    KWWWK............KDBBBBBEEBBBBK.
    KWWWWK...........KDBBBBBEEBBBBBK
    KWWWBBK..........KBBBBBBNHBBBBNN
    KWWBBBBKK........KBBWWWWWWWWWKK.
    KBBBBBBBBKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWWK......
    .KDDBBBBBBBBBBBBBBBBWWWWK.......
    ..KDDDBBBBBBBBBBBBBBBWWWK.......
    ...KKDDDDKBBBBBBBBBBBBBWK.......
    .....KKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    .........KK.KK.....KK.KK........
    ................................
""")

WALK_0 = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .KKK.............KDDBBBBBBBBBK..
    KWWWK............KDBBBBBEEBBBBK.
    KWWWWK...........KDBBBBBEEBBBBBK
    KWWWBBK..........KBBBBBBNHBBBBNN
    KWWBBBBKK........KBBWWWWWWWWWKK.
    KBBBBBBBBKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWWK......
    .KDDBBBBBBBBBBBBBBBBWWWWK.......
    ..KDDDBBBBBBBBBBBBBBBWWWK.......
    ...KKDDDDKBBBBBBBBBBBBBWK.......
    .....KKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    .......KSSKTTK.....KSSKTTK......
    .......KSSKTTK.....KSSKTTK......
    ......KSSKTTK.......KSSKTTK.....
    ......KSSKTTK.......KSSKTTK.....
    .......KK.KK.........KK.KK......
    ................................
""")

WALK_1 = art("""
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .KKK.............KDDBBBBBBBBBK..
    KWWWK............KDBBBBBEEBBBBK.
    KWWWWK...........KDBBBBBEEBBBBBK
    KWWWBBK..........KBBBBBBNHBBBBNN
    KWWBBBBKK........KBBWWWWWWWWWKK.
    KBBBBBBBBKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWWK......
    .KDDBBBBBBBBBBBBBBBBWWWWK.......
    ..KDDDBBBBBBBBBBBBBBBWWWK.......
    ...KKDDDDKBBBBBBBBBBBBBWK.......
    .....KKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    .........KKKTTK...KSSKKK........
    ............KK.....KK...........
    ................................
""")

WALK_2 = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .KKK.............KDDBBBBBBBBBK..
    KWWWK............KDBBBBBEEBBBBK.
    KWWWWK...........KDBBBBBEEBBBBBK
    KWWWBBK..........KBBBBBBNHBBBBNN
    KWWBBBBKK........KBBWWWWWWWWWKK.
    KBBBBBBBBKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWWK......
    .KDDBBBBBBBBBBBBBBBBWWWWK.......
    ..KDDDBBBBBBBBBBBBBBBWWWK.......
    ...KKDDDDKBBBBBBBBBBBBBWK.......
    .....KKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    .........KSSKTTK.KSSKTTK........
    .........KSSKTTK.KSSKTTK........
    ..........KK.KK...KK.KK.........
    ................................
""")

WALK_3 = art("""
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .KKK.............KDDBBBBBBBBBK..
    KWWWK............KDBBBBBEEBBBBK.
    KWWWWK...........KDBBBBBEEBBBBBK
    KWWWBBK..........KBBBBBBNHBBBBNN
    KWWBBBBKK........KBBWWWWWWWWWKK.
    KBBBBBBBBKK.....KBBWWWWWWWKKK...
    KBBBBBBBBBBKKKKKBBBBWWWWWK......
    KDBBBBBBBBBBBBBBBBBBWWWWWK......
    .KDBBBBBBBBBBBBBBBBBWWWWWK......
    .KDDBBBBBBBBBBBBBBBBWWWWK.......
    ..KDDDBBBBBBBBBBBBBBBWWWK.......
    ...KKDDDDKBBBBBBBBBBBBBWK.......
    .....KKKKKDDDDDDDDDDDDDDK.......
    ........KBBKDDKKKKKBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KBBKDDK...KBBKDDK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKTTK...KSSKTTK.......
    ........KSSKKK.....KKKTTK.......
    .........KK...........KK........
    ................................
""")

SIT_A = art("""
    ................................
    .................K...K..........
    ................KSK.KSK.........
    ...............KSSDKSWBK........
    ...............KSDDKSWBBK.......
    ...............KDDBBBBBBBK......
    ..............KDDBBBBBBBBBK.....
    ..............KDBBBBBEEBBBBK....
    ..............KDBBBBBEEBBBBBK...
    ..............KBBBBBBNHBBBBNN...
    ..............KBBWWWWWWWWWKK....
    .............KBBWWWWWWWKKK......
    ............KBBBBWWWWWWK........
    ...........KBBBBBWWWWWWK........
    ..........KBBBBBBBWWWWWK........
    .........KBBBBBBBBBWWWWK........
    .........KBBBBBBBBBKWWK.........
    ........KBBBBBKKBBBKSSK.........
    ........KBBBBBBBKBBKSSK...KK....
    ........KDBBBBBBBKBKSSK..KWWK...
    .......KDBBBBBBBBKBKSSK.KWWWWK..
    .......KDBBBBBBBKKKKKKKKBWWWWK..
    .......KDBBBBBKKKBBBBBBBBBWWWK..
    .......KDDDKKKBBBBBBBBBBBBBWWK..
    ........KKKDDDDDDDDDDDDDDDDDK...
    ...........KKKKKKKKKKKKKKKKK....
    ................................
""")

SIT_B = art("""
    ................................
    .................K...K..........
    ................KSK.KSK.........
    ...............KSSDKSWBK........
    ...............KSDDKSWBBK.......
    ...............KDDBBBBBBBK......
    ..............KDDBBBBBBBBBK.....
    ..............KDBBBBBEEBBBBK....
    ..............KDBBBBBEEBBBBBK...
    ..............KBBBBBBNHBBBBNN...
    ..............KBBWWWWWWWWWKK....
    .............KBBWWWWWWWKKK......
    ............KBBBBWWWWWWK........
    ...........KBBBBBWWWWWWK........
    ..........KBBBBBBBWWWWWK........
    .........KBBBBBBBBBWWWWK........
    .........KBBBBBBBBBKWWK.........
    ........KBBBBBKKBBBKSSK.........
    ........KBBBBBBBKBBKSSK....KK...
    ........KDBBBBBBBKBKSSK...KWWK..
    .......KDBBBBBBBBKBKSSK.KKWWWWK.
    .......KDBBBBBBBKKKKKKKKBWWWWWK.
    .......KDBBBBBKKKBBBBBBBBBWWWK..
    .......KDDDKKKBBBBBBBBBBBBBWWK..
    ........KKKDDDDDDDDDDDDDDDDDK...
    ...........KKKKKKKKKKKKKKKKK....
    ................................
""")

CARRIED_A = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .................KDDBBBBBBBBBK..
    .................KDBBBBBEEBBBBK.
    .................KDBBBBBEEBBBBBK
    .................KBBBBBBNHBBBBNN
    .................KBBWWWWWWWWWKK.
    ................KBBWWWWWWWKKK...
    .........KKKKKKKBBBBWWWWWK......
    .......KKBBBBBBBBBBBWWWWWK......
    .....KKBBBBBBBBBBBBBWWWWWK......
    ....KBBBBBBBBBBBBBBBWWWWK.......
    ...KBBBBBBKBBBBBBBBBBWWWK.......
    ..KBBBBBBDKBBBBBBBBBBBBWK.......
    .KBBBBBBDDKDDDDDDDDDDDDDK.......
    .KBBBBBDDKBBKDDKKKKBBKDDK.......
    KBBBBBDDKKBBKDDK..KBBKDDK.......
    KWWBBDDK.KBBKDDK..KBBKDDK.......
    KWWWDDK..KSSKTTK..KSSKTTK.......
    KWWWWK...KSSKTTK..KSSKTTK.......
    .KWWK....KSSKTTK..KSSKTTK.......
    ..KK.....KSSKTTK..KSSKTTK.......
    ..........KK.KK....KK.KK........
""")

CARRIED_B = art("""
    ................................
    ....................K...K.......
    ...................KSK.KSK......
    ..................KSSDKSWBK.....
    ..................KSDDKSWBBK....
    ..................KDDBBBBBBBK...
    .................KDDBBBBBBBBBK..
    .................KDBBBBBEEBBBBK.
    .................KDBBBBBEEBBBBBK
    .................KBBBBBBNHBBBBNN
    .................KBBWWWWWWWWWKK.
    ................KBBWWWWWWWKKK...
    .........KKKKKKKBBBBWWWWWK......
    .......KKBBBBBBBBBBBWWWWWK......
    .....KKBBBBBBBBBBBBBWWWWWK......
    ....KBBBBBBBBBBBBBBBWWWWK.......
    ...KBBBBBBKBBBBBBBBBBWWWK.......
    ..KBBBBBBDKBBBBBBBBBBBBWK.......
    .KBBBBBBDDKDDDDDDDDDDDDDK.......
    .KBBBBBDDKBBKDDKKKKBBKDDK.......
    KBBBBBDDKKBBKDDK..KBBKDDK.......
    KWWBBDDK.KBBKDDK..KBBKDDK.......
    KWWWDDK.KSSKTTK....KSSKTTK......
    KWWWWK..KSSKTTK....KSSKTTK......
    .KWWK..KSSKTTK......KSSKTTK.....
    ..KK...KSSKTTK......KSSKTTK.....
    ........KK.KK........KK.KK......
""")

FOX = Species(
    key="fox",
    label=QT_TRANSLATE_NOOP("Species", "Fox"),
    palette={
        "K": "#2e1812",  # outline
        "B": "#e2632f",  # red-orange fur
        "D": "#a9431f",  # dark fur: far ear and legs, belly, underside of the tail
        "W": "#fbf5ec",  # white: muzzle, cheeks, chest, inside of the ear, tip of the tail
        "N": "#1e1311",  # nose, pupil
        EYE: "#1e1311",
        EYE_SHINE: "#ffffff",
        "S": "#5c4640",  # black stockings, backs of the ears
        "T": "#46342f",  # far stockings
    },
    animations={
        # Swishing its tail, now and then turning an ear back.
        Activity.STANDING: Animation(
            (STAND_A, STAND_B, STAND_A, STAND_B, STAND_A, STAND_A, STAND_C, STAND_A), fps=2
        ),
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_3), fps=8),  # trotting
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # tail around its paws, tip twitching
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),  # kicking, tail hanging
    },
    gait=Gait(speed=50, max_slope=0.4, distance=(80, 320)),
)
