"""The frog: a green frog that hops around, and croaks now and then while it sits."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, Frame, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....................KKK.........
    ...................KBBBK........
    ..................KBEEEBK.......
    ...........KKKKKKKKBNNHBKKK.....
    .........KKBBBDDBBBBEEEBBBBKK...
    .......KKBBBBBDDBBBBBBBBBBBBBK..
    ......KBBDDBBBBBBBBNBBBBBBBBBBK.
    .....KBBBDDBBBBBBBBBNNNNNNNNNNK.
    ....KBBBBBBBBBBBBBBBBWWWWWWWWK..
    ....KBBBBBKKKKKKBBBBBBWWWWWWK...
    ...KBBBBKKBBBBBBKKBBBBBWWWWK....
    ...KBBBKBBBBBBBBBBKBBBBKKKK.....
    ...KBBKBBBBBBBBBBBKBBBBK........
    ...KBKBBBBBBBBBBBBKBBBK.........
    ...KKBBBBBBBBBBBBBKBBBK.........
    ...KBBBBBBBBBBBBBBBKBBBK........
    ...KDBBBBBBBBBBBBBBBKBBBK.......
    ....KDDDDDDDDDDDDKKKKKBBBKKKKK..
    ....KBBBBBBBBBBBBBBKBBKBBKBKBK..
    .....KKKKKKKKKKKKKKKKKKKKKKKK...
    ................................
""")

# Breathing: the throat puffs out a pixel.
STAND_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....................KKK.........
    ...................KBBBK........
    ..................KBEEEBK.......
    ...........KKKKKKKKBNNHBKKK.....
    .........KKBBBDDBBBBEEEBBBBKK...
    .......KKBBBBBDDBBBBBBBBBBBBBK..
    ......KBBDDBBBBBBBBNBBBBBBBBBBK.
    .....KBBBDDBBBBBBBBBNNNNNNNNNNK.
    ....KBBBBBBBBBBBBBBBBWWWWWWWWK..
    ....KBBBBBKKKKKKBBBBBBWWWWWWWK..
    ...KBBBBKKBBBBBBKKBBBBBWWWWWK...
    ...KBBBKBBBBBBBBBBKBBBBKKKKK....
    ...KBBKBBBBBBBBBBBKBBBBK........
    ...KBKBBBBBBBBBBBBKBBBK.........
    ...KKBBBBBBBBBBBBBKBBBK.........
    ...KBBBBBBBBBBBBBBBKBBBK........
    ...KDBBBBBBBBBBBBBBBKBBBK.......
    ....KDDDDDDDDDDDDKKKKKBBBKKKKK..
    ....KBBBBBBBBBBBBBBKBBKBBKBKBK..
    .....KKKKKKKKKKKKKKKKKKKKKKKK...
    ................................
""")

# Pushing off: tipped up, the hind feet still on the ground behind it.
HOP_PUSH = art("""
    ................................
    ................................
    .....................KKK........
    ....................KBBBK.......
    ...................KBEEEBK......
    ...............KKKKKBNNHBKKK....
    .............KKBBBBBBEEEBBBBKK..
    ...........KKBBBDDBBBBBBBBBBBBK.
    ..........KBBBBBDDBBNBBBBBBBBBBK
    .........KBBDDBBBBBBBNNNNNNNNNNK
    ........KBBBDDBBBBBBBBWWWWWWWWK.
    .......KBBBBBBBBBBBBBBBWWWWWWK..
    ......KBBBBBBBBBBBBBBBBWWWWWK...
    .....KBBBBBBKKKKBBBBBBBBWWWK....
    .....KBBBBKKBBBBKKBBBBBKKKK.....
    ....KBBBBKBBBBBBBBKBBBBK........
    ....KBBBKBBBBBBBBBKBBBBK........
    ...KBBBKBBBBBBBBBBKDKBBBK.......
    ...KBBKBBBBBBBBBBKKKKKBBBK......
    ..KBBBKBBBBBBBBBK....KBKBK......
    ..KBBKDDBBBBBBKK......K.K.......
    .KBBKKKDDDDDKK..................
    .KBBK..KKKKK....................
    KBBBKK..........................
    KBBBKBK.........................
    .KKKKKK.........................
    ................................
""")

# Landing: on its front feet, the rump still up and the hind feet off the ground.
HOP_LAND = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .....................KKK........
    ....................KBBBK.......
    .........KKKK......KBEEEBK......
    .......KKBBBBKKKKKKKBNNHBKKK....
    ......KBBBDDBBBBBBBBBEEEBBBBKK..
    .....KBBBBDDBBBBBBBBBBBBBBBBBBK.
    .....KBDDBBBBBBBBBBBNBBBBBBBBBBK
    ....KBBDDBBBBBBBBBBBBNNNNNNNNNNK
    ....KBBBBKKKKKKBBBBBBBWWWWWWWWK.
    ....KBBKKBBBBBBKKBBBBBBWWWWWWK..
    ....KBKBBBBBBBBBBKBBBBBBWWWWK...
    ....KKBBBBBBBBBBBBKBBBBKKKKK....
    ....KBBBBBBBBBBBBBKBBBBK........
    ....KBBBBBBBBBBBBKDKBBBK........
    .....KDDDDDDDDDDKKKKBBBK........
    ....KBBBBKKKKKKKK...KBBBK.......
    ...KBBBBK............KBBBK......
    ...KKKKK..............KBBBKKKK..
    ......................KBBKBKBK..
    .......................KKKKKK...
    ................................
""")

# Resting in its crouch, its eyelids half down...
SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....................KKK.........
    ...................KBBBK........
    ..................KBBBBBK.......
    ...........KKKKKKKKBNNHBKKK.....
    .........KKBBBDDBBBBEEEBBBBKK...
    .......KKBBBBBDDBBBBBBBBBBBBBK..
    ......KBBDDBBBBBBBBNBBBBBBBBBBK.
    .....KBBBDDBBBBBBBBBNNNNNNNNNNK.
    ....KBBBBBBBBBBBBBBBBWWWWWWWWK..
    ....KBBBBBKKKKKKBBBBBBWWWWWWK...
    ...KBBBBKKBBBBBBKKBBBBBWWWWK....
    ...KBBBKBBBBBBBBBBKBBBBKKKK.....
    ...KBBKBBBBBBBBBBBKBBBBK........
    ...KBKBBBBBBBBBBBBKBBBK.........
    ...KKBBBBBBBBBBBBBKBBBK.........
    ...KBBBBBBBBBBBBBBBKBBBK........
    ...KDBBBBBBBBBBBBBBBKBBBK.......
    ....KDDDDDDDDDDDDKKKKKBBBKKKKK..
    ....KBBBBBBBBBBBBBBKBBKBBKBKBK..
    .....KKKKKKKKKKKKKKKKKKKKKKKK...
    ................................
""")

# ...and breathing.
SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....................KKK.........
    ...................KBBBK........
    ..................KBBBBBK.......
    ...........KKKKKKKKBNNHBKKK.....
    .........KKBBBDDBBBBEEEBBBBKK...
    .......KKBBBBBDDBBBBBBBBBBBBBK..
    ......KBBDDBBBBBBBBNBBBBBBBBBBK.
    .....KBBBDDBBBBBBBBBNNNNNNNNNNK.
    ....KBBBBBBBBBBBBBBBBWWWWWWWWK..
    ....KBBBBBKKKKKKBBBBBBWWWWWWWK..
    ...KBBBBKKBBBBBBKKBBBBBWWWWWK...
    ...KBBBKBBBBBBBBBBKBBBBKKKKK....
    ...KBBKBBBBBBBBBBBKBBBBK........
    ...KBKBBBBBBBBBBBBKBBBK.........
    ...KKBBBBBBBBBBBBBKBBBK.........
    ...KBBBBBBBBBBBBBBBKBBBK........
    ...KDBBBBBBBBBBBBBBBKBBBK.......
    ....KDDDDDDDDDDDDKKKKKBBBKKKKK..
    ....KBBBBBBBBBBBBBBKBBKBBKBKBK..
    .....KKKKKKKKKKKKKKKKKKKKKKKK...
    ................................
""")

# Croaking: the vocal sac fills up under its chin...
CROAK_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....................KKK.........
    ...................KBBBK........
    ..................KBEEEBK.......
    ...........KKKKKKKKBNNHBKKK.....
    .........KKBBBDDBBBBEEEBBBBKK...
    .......KKBBBBBDDBBBBBBBBBBBBBK..
    ......KBBDDBBBBBBBBNBBBBBBBBBBK.
    .....KBBBDDBBBBBBBBBNNNNNNNNNNK.
    ....KBBBBBBBBBBBBBBBBWWWWWWWWK..
    ....KBBBBBKKKKKKBBBBBWWWWWLWWWK.
    ...KBBBBKKBBBBBBKKBBBWWWWWWWWWK.
    ...KBBBKBBBBBBBBBBKBBKYYYYYYYK..
    ...KBBKBBBBBBBBBBBKBBBKKKKKKK...
    ...KBKBBBBBBBBBBBBKBBBK.........
    ...KKBBBBBBBBBBBBBKBBBK.........
    ...KBBBBBBBBBBBBBBBKBBBK........
    ...KDBBBBBBBBBBBBBBBKBBBK.......
    ....KDDDDDDDDDDDDKKKKKBBBKKKKK..
    ....KBBBBBBBBBBBBBBKBBKBBKBKBK..
    .....KKKKKKKKKKKKKKKKKKKKKKKK...
    ................................
""")

# ...and blows up into a bubble as big as its head.
CROAK_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....................KKK.........
    ...................KBBBK........
    ..................KBEEEBK.......
    ...........KKKKKKKKBNNHBKKK.....
    .........KKBBBDDBBBBEEEBBBBKK...
    .......KKBBBBBDDBBBBBBBBBBBBBK..
    ......KBBDDBBBBBBBBNBBBBBBBBBBK.
    .....KBBBDDBBBBBBBBBNNNNNNNNNNK.
    ....KBBBBBBBBBBBBBBBBWWWWWWWWWK.
    ....KBBBBBKKKKKKBBBBBWWWWWLLWWWK
    ...KBBBBKKBBBBBBKKBBBWWWWWLWWWWK
    ...KBBBKBBBBBBBBBBKBBWWWWWWWWWK.
    ...KBBKBBBBBBBBBBBKBBWWWWWWWWK..
    ...KBKBBBBBBBBBBBBKBBKYYYYYYK...
    ...KKBBBBBBBBBBBBBKBBBKKKKKK....
    ...KBBBBBBBBBBBBBBBKBBBK........
    ...KDBBBBBBBBBBBBBBBKBBBK.......
    ....KDDDDDDDDDDDDKKKKKBBBKKKKK..
    ....KBBBBBBBBBBBBBBKBBKBBKBKBK..
    .....KKKKKKKKKKKKKKKKKKKKKKKK...
    ................................
""")

# Held up, its long hind legs dangle in the air and kick: one hangs stretched while the
# other is drawn up, knee toward the belly.
CARRIED_A = art("""
    .....................KKK........
    ....................KBBBK.......
    ...................KBEEEBK......
    ............KKKKKKKKBNNHBKKK....
    ..........KKBBBDDBBBBEEEBBBBKK..
    ........KKBBBBBDDBBBBBBBBBBBBBK.
    .......KBBDDBBBBBBBBNBBBBBBBBBBK
    ......KBBBDDBBBBBBBBBNNNNNNNNNNK
    .....KBBBBBBBBBBBBBBBBWWWWWWWWK.
    .....KBBBBBBBBBBBBBBBBBWWWWWWK..
    ....KBBBBBBBBBBBBBBBBBBBWWWWK...
    ....KBBBBBBBBBBWWWWWBBBBKKKK....
    .....KKBBBBBKWWWWWWKBBBK........
    .....KBBBBBKKKKKKKKKKBBBK.......
    ....KBBBBBKDDDDDK...KBKBK.......
    ....KBBBBKKKDDDDK....K.K........
    ...KBBBBK..KDDDK................
    ...KBBBK..KDDDKK................
    ...KBBK...KDDDDDK...............
    ..KBBBKK..KDKDKDK...............
    ..KBBBBBK..K.K.K................
    ..KBKBKBK.......................
    ...K.K.K........................
    ................................
    ................................
    ................................
    ................................
""")

CARRIED_B = art("""
    .....................KKK........
    ....................KBBBK.......
    ...................KBEEEBK......
    ............KKKKKKKKBNNHBKKK....
    ..........KKBBBDDBBBBEEEBBBBKK..
    ........KKBBBBBDDBBBBBBBBBBBBBK.
    .......KBBDDBBBBBBBBNBBBBBBBBBBK
    ......KBBBDDBBBBBBBBBNNNNNNNNNNK
    .....KBBBBBBBBBBBBBBBBWWWWWWWWK.
    .....KBBBBBBBBBBBBBBBBBWWWWWWK..
    ....KBBBBBBBBBBBBBBBBBBBWWWWK...
    ....KBBBBBBBBBBWWWWWBBBBKKKK....
    .....KKBBBBBKWWWWWWKBBBK........
    ......KBBBBBBKKKKKKKKBBBK.......
    .....KDKKBBBBBBK....KBKBK.......
    .....KDDDKKBBBBK.....K.K........
    ....KDDDDKKBBBK.................
    ....KDDDKKBBBKK.................
    ....KDDK.KBBBBBK................
    ...KDDDKKKBKBKBK................
    ...KDDDDDKK.K.K.................
    ...KDKDKDK......................
    ....K.K.K.......................
    ................................
    ................................
    ................................
    ................................
""")


def croaking(still: Frame, filling: Frame, full: Frame) -> tuple[Frame, ...]:
    """Two croaks in a row: the sac blows up, goes down, blows up again."""
    return (still, filling, full, full, filling, still, filling, full, full, filling, still)


FROG = Species(
    key="frog",
    label=QT_TRANSLATE_NOOP("Species", "Frog"),
    palette={
        "K": "#1d2c10",  # outline
        "B": "#8fca3c",  # leaf-green skin
        "D": "#5a9128",  # darker green: spots, shadows under the body, the far hind leg
        "W": "#f3eeb4",  # pale yellow throat, belly and vocal sac
        "Y": "#e3d98c",  # shade under the blown-up vocal sac
        "L": "#fffdf0",  # shine on the blown-up vocal sac
        "N": "#142010",  # mouth, pupil
        EYE: "#142010",
        EYE_SHINE: "#ffffff",
    },
    animations={
        # Crouching, its throat pulsing as it breathes.
        Activity.STANDING: Animation((STAND_A, STAND_B), fps=2),
        # Little hops: crouched, pushing off with its hind feet, landing on its front feet.
        Activity.WALKING: Animation((STAND_A, HOP_PUSH, HOP_LAND), fps=7),
        # Resting in the same crouch, drowsy and breathing; every 6 s it opens its eyes and
        # croaks twice, its vocal sac blowing up under its chin.
        Activity.SITTING: Animation(
            (SIT_A, SIT_A, SIT_B, SIT_B) * 3 + (SIT_A,) + croaking(STAND_A, CROAK_A, CROAK_B),
            fps=4,
        ),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),  # kicking
    },
    gait=Gait(speed=40, max_slope=0.4, distance=(60, 240)),
    locomotion=Locomotion.HOP,
)
