"""The guinea pig: a tricolor, ginger, white and black, that scurries around."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ...KPPPPPK...........KPPPPK.....
    ....KKKKK.............KKKK......
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWPK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWWK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ...KPPPPPK...........KPPPPK.....
    ....KKKKK.............KKKK......
    ................................
""")

WALK_0 = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ..KPPPPPKKFFK....KFFK.KPPPPK....
    ...KKKKK..KK......KK...KKKK.....
    ................................
""")

WALK_1 = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ....KBBBK.............KWWWK.....
    ....KPPPPK............KPPPK.....
    .....KKKK..............KKK......
    ................................
""")

WALK_2 = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KKBBBBKKKKKKKKKKKKWWWWKK.....
    .KFKKPPPPPK.........KPPPPKFFK...
    .KK..KKKKK...........KKKK.KK....
    ................................
""")

WALK_3 = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWPK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWWK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ....KBBBK.............KWWWK.....
    ....KPPPPK............KPPPK.....
    .....KKKK..............KKK......
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWPPPWWK....
    ...KKKKKKKKKKKKKKKKKKKKKKKK.....
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK................
    .......KKCCCCCCWKK.KK...........
    .....KKBCCCCCCWWWWKDDK..........
    ....KBBCCCCCCCWWWWKDPDKKKKKK....
    ...KBBBCCCCCCWWWWWWKDDKBBBBBK...
    ..KBBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBEEBBWWK.
    .KBBBBBBBCCWWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWPPPWWK....
    ...KKKKKKKKKKKKKKKKKKKKKKKK.....
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ..KBBBBK..............KWWWWK....
    .KBBBK.................KWWWK....
    .KPPPK.................KPPPK....
    ..KKK...................KKK.....
    ................................
""")

CARRIED_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK...KK...........
    .......KKCCCCCCWKKKDDK..........
    .....KKBCCCCCCWWWWKDPDKKKKKK....
    ....KBBCCCCCCCWWWWWKDDKBBBBBK...
    ...KBBBCCCCCCWWWWWWWKKBBBBBBBK..
    ..KBBBBCCCCCCWWWWWWWBBBBEEBBWWK.
    ..KBBBBBCCCCCWWWWWWWBBBBEEBBWWK.
    .KBBBBBBCCCCWWWWWWWWBBBBNHBBWPK.
    .KBBBBBBBCCWWWWWWWWWBBBBBBBWWWK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBBWWNK.
    .KBBBBBBBBBWWWWWWWWWBBBBBBWWWK..
    ..KBBBBBBBBWWWWWWWWWBBBBWWWWK...
    ..KBBBBBBBBWWWWWWWWWWWWWWWWK....
    ...KBBBBKKKKKKKKKKKKKKWWWWK.....
    ....KBBBK............KWWWK......
    ....KBBBK............KWWWK......
    ....KPPPK............KPPPK......
    .....KKK..............KKK.......
    ................................
""")

GUINEA_PIG = Species(
    key="guinea_pig",
    label=QT_TRANSLATE_NOOP("Species", "Guinea Pig"),
    palette={
        "K": "#2b1d16",  # outline
        "B": "#e08a3c",  # ginger fur
        "D": "#b8652b",  # ear
        "W": "#f8f3ea",  # white fur: blaze, band around the body, front legs
        "N": "#1d1411",  # pupil, mouth
        EYE: "#1d1411",
        EYE_SHINE: "#ffffff",
        "C": "#4a4140",  # black patch
        "P": "#f2a7a0",  # nose, inner ear, feet
        "F": "#c9807b",  # far feet
    },
    animations={
        # Sniffing in short bursts: sniff, sniff, pause.
        Activity.STANDING: Animation((STAND_A, STAND_B, STAND_A, STAND_B, STAND_A, STAND_A), fps=4),
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_3), fps=10),  # scurrying
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # lying down like a loaf, breathing
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),  # paddling its legs
    },
    gait=Gait(speed=50, max_slope=0.4, distance=(60, 240)),
)
