"""The octopus: a blue-ringed octopus that crawls on its arms and shows its rings when it stops.

It is golden yellow, with four near arms in front and four far ones, darker, behind. Its blue rings
(A, with C at their centers, on the mantle, the head and the arms) fade away while it crawls and
come back whenever it keeps still or is carried: its colorings are the steps of that fade (see
ring_fade.py). On their way the rings darken to brown before they light up blue, as a real
blue-ringed octopus's do.
"""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import ColorShift, Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

# Standing on its arms, the near ones in front and the far ones behind them, one raised ahead.
STAND_A = art("""
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK.........
    .......KKDDDBBBBBBAAAKKK...KKK..
    .........KKKBBLBBBACABBBK.KPBBK.
    ........KKKKABBBBBAAABBBBKKKKBK.
    ......KKKKBAABBBBBBBBBBBBBAKKAK.
    ...KKKKBBBBAABBBBBBBBBKKBBABBBK.
    ..KFKKBBBBBKKKBBBKKBBBKFKKKBPK..
    ...KBBABKKKFFKBBBKFKBBAKFFKKK...
    .K.KBBKK.KFFKBBBKKFFKAABKFFFKK..
    KBKBBKKBKFFKKBBK.KFFKBBBKKKKKBK.
    KBBBK.KPKKKKBABK..KFKKBBBK..KPK.
    KPBK..KBKKBBBBK...KFFFKBBAKKBBK.
    .KBK..KBBBBBKK.....KFFKKKABBBK..
    ..K....KKKKK........KK...KKKK...
    ................................
""")

# The raised arm and the tips of the others curled a little more.
STAND_B = art("""
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK....KKK..
    .......KKDDDBBBBBBAAAKKK..KBBBK.
    .........KKKBBLBBBACABBBK.KPKAK.
    ........KKKKABBBBBAAABBBBKKKKBK.
    ...K..KKKKBAABBBBBBBBBBBBBAKBBK.
    ..KFKKKBBBBAABBBBBBBBBKKBBABBBK.
    ..KFKKBBBBBKKKBBBKKBBBKFKKKBPK..
    ...KBBABKKKFFKBBBKFKBBAKFFKKK...
    .KKKBBKKKFFFKBBBKKFFKAABKFFFKK..
    KBBBBKKBKFFKKBBK.KFFKBBBKKKKKBK.
    KPBBK.KPKKKKBABK..KFKKBBBK..KPK.
    KBBK..KBKKBBBBK...KFFFKBBAKKBBK.
    .KBK..KBBBBBKK.....KFFKKKABBBK..
    ..K....KKKKK........KK...KKKK...
    ................................
""")

# Crawling: each arm is planted for two frames, its end sliding back, then lifted and swung
# ahead, the near and far ones taking turns; the body bobs a row.
CRAWL_A = art("""
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK.........
    .......KKDDDBBBBBBAAAKKK........
    .........KKKBBLBBBACABBBKK......
    .......KKKKKABBBBBAAABBBBBK.....
    .....KKFKKBAABBBBBBBBKBBBBAK....
    ...KKFKKBBBAAABBBDBBBKKKKAABK...
    ..KFFKABBBBKKKBBBKKBBKFFKKBBBK..
    ...KKBABBKKFKBBBBKKBBBKFK.KBBBK.
    ..KKBBPKK.KKABBBKKKBBBKFFK.KAAK.
    .KBBBBBBKKKBAABK..KAAAKFFK..KPK.
    .KBBBKKBBBBBBKK...KKBBPKFFK.KBK.
    .KPBK..KBBBKK.....KKBBBKFFFK.K..
    ..KBK...KKK........KKBKKKFK.....
    ...K................KKK..K......
    ................................
""")

CRAWL_B = art("""
    ................................
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK.........
    .......KKDDDBBLBBBAAAKKK........
    .........KKKBBBBBBACABBBKK......
    .....K.KKKKAABBBBBAAABBBBBK.....
    ....KFKKKBBAABBBBBBBBBBBBBAK....
    ....KKBBBBBAABBBBBBBBKKKBAABK...
    ...KBABBBBBKKKBBBKKBBBKFKKBBBK..
    K.KBBAAKPKKFFKBBBKKBBAPKFKKBBK..
    BKBBBKKKBKFFKABBKKFKABBKFFFKBBK.
    BKBBK..KBBKKBAAK.KFKBBBKKFKKAAK.
    PBBK....KBBBBBK..KFFKBK..K..KPK.
    BBK......KKKKK....KFFK......KBK.
    KK.................KK........K..
    ................................
""")

CRAWL_C = art("""
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK.........
    .......KKDDDBBBBBBAAAKK.........
    .........KKKBBLBBBACABBKK.......
    ........KKKAABBBBBAAABBBBK......
    ......KKBBBAABBBBBBBBBBBBBK.....
    ....KKBBBBBAABBBBBBBBKKBBABK....
    K..KBABBBBKKKKBBBKKBBBKKKBBK....
    BKKBBBKKKKFFFKBBBKFKBBKFKBBBK...
    PKBBKK..KFFKKKBBKKFKBAAKBPBBK...
    BBBK...KBKK.KBBBKKFFKBBKBBKAKK..
    KBK....KPK.KBAAK..KFKBBBBKKBBK..
    .K.....KBKKBBBK....KKKKBK.KBPK..
    ........KBBBKK.........K...KBK..
    .........KKK................K...
    ................................
""")

CRAWL_D = art("""
    ................................
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBBK.........
    .......KKDDDBBLBBBAAABKKK.......
    .........KKKBBBBBBACABBBBK......
    ......KKKKKAABBBBBAAABBBBBK.....
    ..K.KKKKBBBAABBBBBBBBKBBBABK....
    .KFKFKABBBBAAABBBDBBBKKKKBBBK...
    .KKKKBAABBKKKKBBBKKBBBKFFKBBKK..
    .KBBBBKKKKKKKBBBBKKBBBKFFFKAAPK.
    .KPBBKK.....KBBBK.KKBAAKKFKBBBK.
    .KBBKPBK..KKABBK..KFKBBKPKFKBK..
    ..KK.KBKKKBBBAK....KKBBBBKFFKK..
    .....KBBBBBBKK......KKBBBKKFFK..
    ......KKKKKK..........KKK..KK...
    ................................
""")

# Resting low on the ground, its arms curled around it.
REST_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......KKKK......................
    ....KKLLLLKK....................
    ...KLLBBBAAAKK..................
    ...KLAAABACABBK.................
    ..KLBACABAAABBBK................
    ..KLBAAABBBBBBBK..KK............
    ..KDBBBBBBBBAAABKKBBK...........
    ...KBBBAAABLACABBBEEBK...K......
    ...KDBBACABBAAABBBNHBK..KFK.....
    ....KBDAAABBBBBBBBBBBBKKKFK.....
    ...KKFKDDLBBBBBBBBBBBBFFFFKKKK..
    .KKBKFKKKBBBBBBLBBAAABKKFKKBPBK.
    KBPKKFFFFKKABBBBBBACABBBKK.KKBK.
    KBBKKKKKKBBABBBBBBAAABBBBBKKKBK.
    .KBBBBBBBBBAABBDDDBBBBBBBBBABBK.
    ..KBBBBBBBKKKFFKKKBBBBKKKBBABK..
    ...KKKKKKK...KK...KKKK...KKKK...
    ................................
""")

REST_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......KKKK......................
    ....KKLLLLKK....................
    ...KLLBBBAAAKK..................
    ...KLAAABACABBK.................
    ..KLBACABAAABBBK................
    ..KLBAAABBBBBBBK..KK............
    ..KDBBBBBBBBAAABKKBBK...........
    ...KBBBAAABLACABBBEEBK...K......
    ...KDBBACABBAAABBBNHBK..KFK.....
    ....KBDAAABBBBBBBBBBBBKKKFK.....
    ..KKKFKDDLBBBBBBBBBBBBFFFFK.KK..
    .KPBKFKKKBBBBBBLBBAAABKKFK.KPBK.
    KBBKKFFFFKKABBBBBBACABBBKK..KBK.
    KBBKKKKKKBBABBBBBBAAABBBBBKKKBK.
    .KBBBBBBBBBAABBDDDBBBBBBBBBABBK.
    ..KBBBBBBBKKKFFKKKBBBBKKKBBABK..
    ...KKKKKKK...KK...KKKK...KKKK...
    ................................
""")

# Held up, its arms droop in a loose bunch, curling at the tips, and sway.
CARRIED_A = art("""
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK.........
    .......KKDDDBBBBBBAAAKK.........
    .........KKKBBLBBBACABBKK.......
    ..........KKABBBBBAAABBBBK......
    .........KBAABBBBBBBBBBBBBK.....
    ........KBBBAABBBBBBBBKBBBBK....
    .......KBBBBKBBBBKKBBBKKKBAAK...
    ......KBBBKKKBBBKKFKBBKFFKABK...
    .....KBBBKFFKAAKFKFKAAAKFFKBBK..
    ....KAABKFFKKBBKFKFKBBBKFFKBBK..
    ....KBBKFFK.KBBKFKFKBBK.KKKKAK..
    ....KBKPKK.KBBKKFFFKKBBKKBPBAK..
    ....KBBBK..KBBK.KFFKKBBK.KBBBK..
    .....KKK....KK...KK..KK...KKK...
    ................................
""")

CARRIED_B = art("""
    ................................
    ................................
    .....KKKKK......................
    ....KLLLLLKK....................
    ...KLBBBBAAAK...................
    ..KLBAAABACABK..................
    ..KLBACABAAABBK.................
    ..KLBAAABBBBBBBK.KKK............
    ..KDBBBBBBBBAAAKKBBBK...........
    ...KBBBAAABLACABBBEEBK..........
    ...KDBBACABBAAABBBNHBK..........
    ....KDDAAABBBBBBBBBBBK..........
    .....KKDDLBBBBBBBBBBBDK.........
    .......KKDDDBBBBBBAAAKK.........
    .........KKKBBLBBBACABBKK.......
    ..........KKABBBBBAAABBBBK......
    .........KBAABBBBBBBBBBBBBK.....
    ........KBBBAABBBBBBBKKBBBBK....
    .......KBBBBKBBBBKKBBBKKKBAK....
    ......KBBBKKKBBBKKKBBBKFKABK....
    ......KBBKFKAABKFKFKBAAKFKBBK...
    ......KAKKFKBBAKFKKFKBBKFKBBK...
    .....KBBKKKBBBKFK.KFKBBBKKABK...
    ......KBKPKBBKKFK.KFFKBBPKBK....
    ......KBBBBBK.KFK..KFKKBBBBK....
    .......KKKKK...K....K..KKKK.....
    ................................
""")


COLORS = {
    "K": "#3b2806",  # outline
    "B": "#c79b31",  # golden yellow body
    "D": "#9a742a",  # shade under the mantle and the head
    "L": "#e2bc58",  # light on the mantle's rim, pale tubercles
    "F": "#7f5f1d",  # the far arms
    "P": "#ecd690",  # suckers
    "N": "#1e1408",  # pupil
    EYE: "#24170a",
    EYE_SHINE: "#ffffff",
}
BLUE = "#1f63ea"  # the rings at their brightest
CENTER = "#6b4a08"  # the dark brown inside a ring
STEPS = 10  # steps of the fade after the usual palette, the last with no rings


def _blend(a: str, b: str, t: float) -> str:
    """The color `t` of the way from `a` to `b`, mixed in linear light."""

    def channel(i: int) -> int:
        x, y = (int(color[1 + 2 * i : 3 + 2 * i], 16) / 255 for color in (a, b))
        return round(255 * ((1 - t) * x**2.2 + t * y**2.2) ** (1 / 2.2))

    return "#" + "".join(f"{channel(i):02x}" for i in range(3))


def _with_rings(shown: float) -> dict[str, str]:
    """The palette with the rings `shown` of the way in, from 0 (gone) to 1 (at their brightest).

    The rings darken from the body's yellow to brown, then light up from brown to blue.
    """
    body = COLORS["B"]
    darkened = _blend(body, CENTER, min(shown * 2, 1))
    ring = _blend(darkened, BLUE, max(shown * 2 - 1, 0))
    return COLORS | {"A": ring, "C": _blend(body, CENTER, shown)}


FADE = tuple(_with_rings(1 - step / STEPS) for step in range(STEPS + 1))

OCTOPUS = Species(
    key="octopus",
    label=QT_TRANSLATE_NOOP("Species", "Octopus"),
    palette=FADE[0],  # the rings at their brightest: how it looks in the dialogs and the README
    animations={
        # Keeping still, its raised arm and the tips of the others curl and uncurl.
        Activity.STANDING: Animation((STAND_A, STAND_A, STAND_B, STAND_B), fps=2),
        # Crawling: its arms take turns, half of them on the ground sliding back while the others
        # swing ahead, and its body bobs.
        Activity.WALKING: Animation((CRAWL_A, CRAWL_B, CRAWL_C, CRAWL_D), fps=5),
        # Resting low on the ground, its arms curled around it, their tips stirring.
        Activity.SITTING: Animation((REST_A, REST_A, REST_B, REST_B), fps=2),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=3),  # the arms dangling, swaying
    },
    gait=Gait(speed=25, max_slope=0.4, distance=(60, 240), rest=(3.0, 7.0)),
    locomotion=Locomotion.CRAWL,
    sit_label=QT_TRANSLATE_NOOP("PetWindow", "Rest"),
    colorings=FADE[1:],
    color_shift=ColorShift.FADE,
)
