"""The owl: a brown tropical screech owl with ear tufts and yellow eyes, that flies around."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    .......................K........
    ...............K......KDK.......
    ...............KDKKKKKMDK.......
    ..............KMDMMMMMMDMK......
    .............KMMDMMMMRBBBK......
    .............KMMMMDMRBBBBBK.....
    .............KMDMMMRBEEEBBK.....
    .............KMMMDMRBHNHBBK.....
    .............KMMMMMRBEEEBPK.....
    .............KMDMMMMRBBBBPPK....
    ............KMMMMMMMMRBBBQK.....
    ...........KMMMMMMMMMMRRLK......
    ..........KMMSMSMSMMDLTLLK......
    .........KMMMMDMMMMMDLLTLK......
    .........KMMDMMMMMMMDLLLLK......
    .........KMMMMMMMMMMDLLTLK......
    .........KDMMMMMMMMDLLLTLK......
    .........KDDSDDSDMMDLTLLK.......
    ........KDDDSDDSDDDLTLLLK.......
    .......KDDSDDDSDDDLLLTLK........
    ......KDDSDDDKLLLLLLLLK.........
    .....KDDK.....KTKKLLK...........
    ......KK......KGGKFFFK..........
    ..............KKKKKKKK..........
    ................................
""")

# Its head turned to look at you.
STAND_B = art("""
    ................................
    ................................
    ...............K........K.......
    ...............KDK....KDK.......
    ..............KMDKKKKKKDMK......
    ..............KMMMMMMMMMMK......
    .............KMRRRRMMRRRRMK.....
    .............KRBBBBRRBBBBRK.....
    .............KRBEEEBBEEEBRK.....
    .............KRBHNHBBHNHBRK.....
    .............KRBEEEPPEEEBRK.....
    .............KMRBBBPPBBBRMK.....
    .............KMMRBBQQBBRMMK.....
    ...........KMMMMMMMMMMMLLK......
    ..........KMMSMSMSMMDLTLLK......
    .........KMMMMDMMMMMDLLTLK......
    .........KMMDMMMMMMMDLLLLK......
    .........KMMMMMMMMMMDLLTLK......
    .........KDMMMMMMMMDLLLTLK......
    .........KDDSDDSDMMDLTLLK.......
    ........KDDDSDDSDDDLTLLLK.......
    .......KDDSDDDSDDDLLLTLK........
    ......KDDSDDDKLLLLLLLLK.........
    .....KDDK.....KTKKLLK...........
    ......KK......KGGKFFFK..........
    ..............KKKKKKKK..........
    ................................
""")

FLY_0 = art("""
    ................................
    ................................
    ................................
    .......KKKK.....................
    ......KDSDDKK............K......
    .....KDDSDDMMK...K......KDK.....
    .....KDSDDSDMMK..KDKKKKKMDK.....
    .....KDDSDDSMSMKKMDMMMMMMDMK....
    ......KDSDDMMMMKMMDMMMMRBBBK....
    ......KDDSDMMSMKMMMMDMRBBBBBK...
    .......KDSDMMMMKMDMMMRBEEEBBK...
    ........KKDMMSMKMMMDMRBHNHBBK...
    .......KKMKKMMMKMMMMMRBEEEBPK...
    .....KKMMMMMMMMKMDMMMMRBBBBPPK..
    ..KKKMMMMMMMMMMMMMMMMMMRBBBQK...
    .KDSDMMMMMMMMMMMMMMMMMLLLK......
    KDSDDMMMMMMMMMMMMMMLLTLLLLK.....
    .KKKKDMMMMMMMMMLLLTLLLTLLK......
    ......KKMMMLLLTLLLLTLLLK........
    ........KKLLLLLTLLLLKK..........
    ..........KKKKKKKKKK............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
""")

FLY_1 = art("""
    ................................
    ................................
    ................................
    ................................
    .........................K......
    .................K......KDK.....
    .................KDKKKKKMDK.....
    ................KMDMMMMMMDMK....
    ...............KMMDMMMMRBBBK....
    .........KKKKKKKMMMMDMRBBBBBK...
    ......KKKMMMSMMKMDMMMRBEEEBBK...
    ...KKKDDMMMMMSMKMMMDMRBHNHBBK...
    .KKDSDDSDDMMMMMKMMMMMRBEEEBPK...
    KDDSDDSDDSDDMMMKMDMMMMRBBBBPPK..
    .KKDSDDSDDSDDDKMMMMMMMMRBBBQK...
    .KDKKKKKKKKKKKMMMMMMMMLLLK......
    KDSDDMMMMMMMMMMMMMMLLTLLLLK.....
    .KKKKDMMMMMMMMMLLLTLLLTLLK......
    ......KKMMMLLLTLLLLTLLLK........
    ........KKLLLLLTLLLLKK..........
    ..........KKKKKKKKKK............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
""")

FLY_2 = art("""
    ................................
    ................................
    ................................
    ................................
    .........................K......
    .................K......KDK.....
    .................KDKKKKKMDK.....
    ................KMDMMMMMMDMK....
    ...............KMMDMMMMRBBBK....
    ...............KMMMMDMRBBBBBK...
    ...............KMDMMMRBEEEBBK...
    .........KKKKKKKMMMDMRBHNHBBK...
    .......KKMKKKKKKMMMMMRBEEEBPK...
    .....KKMKKMMMSMKMDMMMMRBBBBPPK..
    ..KKKMMKMMSMMMMMMMMMMMMRBBBQK...
    .KDSDMKDMMMMSMMMKMMMMMLLLK......
    KDSDDMKDSDMMMMMKMMMLLTLLLLK.....
    .KKKKKDDSDDMMMKLLLTLLLTLLK......
    .....KDSDDSDMKTLLLLTLLLK........
    .....KDDSDDSDKLTLLLLKK..........
    .....KDSDDSDKKKKKKKK............
    .....KDDSDDK....................
    ......KDSDK.....................
    ......KKKK......................
    ................................
    ................................
    ................................
""")

# Resting as owls roost: upright, fluffed up over its feet, its eyes half closed.
REST_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ...............K.......K........
    ...............KDKKKKKMDK.......
    ..............KMDMMMMMMDMK......
    .............KMMDMMMMRBBBK......
    .............KMMMMDMRBBBBBK.....
    .............KMDMMMRBBBBBBK.....
    .............KMMMDMRBHNHBBK.....
    .............KMMMMMRBEEEBPK.....
    .............KMDMMMMRBBBBPPK....
    .............MMMMMMMMRBBBQK.....
    ...........KMMMMMMMMMMRRLK......
    ..........KMMSMSMSMMDLTLLLK.....
    .........KMMMMDMMMMMDLLTLLK.....
    ........KMMMDMMMMMMMDLLLLLK.....
    ........KMMMMMMMMMMMDLLLTLK.....
    ........KDMMMMMMMMMDLLTLLLK.....
    ........KDDSDDSDDMMDLLTLLK......
    ........KDDDSDDSDDDLLLTLK.......
    .......KDDSDDDSDDDLLLLLLK.......
    ......KDDSDDKLLGGLLFFLK.........
    ......KKKKKKKKKKKKKKKKK.........
    ................................
""")

REST_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...............K.......K........
    ...............KDKKKKKMDK.......
    ..............KMDMMMMMMDMK......
    .............KMMDMMMMRBBBK......
    .............KMMMMDMRBBBBBK.....
    .............KMDMMMRBBBBBBK.....
    .............KMMMDMRBHNHBBK.....
    .............KMMMMMRBEEEBPK.....
    .............KMDMMMMRBBBBPPK....
    ...........KMMMMMMMMMRBBBQK.....
    ..........KMMSMSMSMMDLTLLLK.....
    .........KMMMMDMMMMMDLLTLLK.....
    ........KMMMDMMMMMMMDLLLLLK.....
    ........KMMMMMMMMMMMDLLLTLK.....
    ........KDMMMMMMMMMDLLTLLLK.....
    ........KDDSDDSDDMMDLLTLLK......
    ........KDDDSDDSDDDLLLTLK.......
    .......KDDSDDDSDDDLLLLLLK.......
    ......KDDSDDKLLGGLLFFLK.........
    ......KKKKKKKKKKKKKKKKK.........
    ................................
""")

CARRIED_A = art("""
    ................................
    .......................K........
    ...............K......KDK.......
    ...............KDKKKKKMDK.......
    ....KKKK......KMDMMMMMMDMK......
    ...KDSDDKK...KMMDMMMMRBBBK......
    ..KDDSDDMMK..KMMMMDMRBBBBBK.....
    ..KDSDDSDMMK.KMDMMMRBEEEBBK.....
    ..KDDSDDSMSMKKMMMDMRBHNHBBK.....
    ...KDSDDMMMMMKMMMMMRBEEEBPK.....
    ...KDDSDMMSMMKMDMMMMRBBBBPPK....
    ....KDSDMMMMMMMMMMMMMRBBBQK.....
    .....KKDMMSMMMKMMMMMMMRRLK......
    .......KKMMMMMKMMMMMMLLTLLK.....
    .........KMMMMMMMMMLLLLTLK......
    .........KMMMMMMMLLTLLLLLK......
    .........KMMMMMMLLLLLLTLLK......
    .........KMMMMMLLLTLLLLTLK......
    .........KDMMMLLLLLLTLLLK.......
    ........KDDDMLLLTLLLLLLK........
    .......KDDSDKLLLLLLLTLK.........
    ......KDDSDKKLLLLLLLLK..........
    .....KDDK....KKTKKLKK...........
    ......KK......KTKKLK............
    ..............KGGKFFFK..........
    ..............KKKKKKKK..........
    ................................
""")

CARRIED_B = art("""
    ................................
    .......................K........
    ...............K......KDK.......
    ...............KDKKKKKMDK.......
    ..............KMDMMMMMMDMK......
    .............KMMDMMMMRBBBK......
    .............KMMMMDMRBBBBBK.....
    .............KMDMMMRBEEEBBK.....
    .............KMMMDMRBHNHBBK.....
    .............KMMMMMRBEEEBPK.....
    .............KMDMMMMRBBBBPPK....
    .............MMMMMMMMRBBBQK.....
    ..........KKKKKKKKMMMMRRLK......
    ........KKMMMSMMMMKMMLLTLLK.....
    .......KMMSMMMMMMKMLLLLTLK......
    ......KDMMMMSMMMKLLTLLLLLK......
    ......KDSDMMMMMKLLLLLLTLLK......
    .....KDDSDDMMMKLLLTLLLLTLK......
    .....KDSDDSDMKLLLLLLTLLLK.......
    .....KDDSDDSDKLLTLLLLLLK........
    .....KDSDDSDKLLLLLLLTLK.........
    .....KDDSDDKKLLLLLLLLK..........
    .....KKDSDK..KKTKKLKK...........
    ......KKKK....KTKKLK............
    ..............KGGKFFFK..........
    ..............KKKKKKKK..........
    ................................
""")

OWL = Species(
    key="owl",
    label=QT_TRANSLATE_NOOP("Species", "Owl"),
    palette={
        "K": "#2a201b",  # outline
        "B": "#d8c09a",  # facial disc; the eye sits in it, so a blink closes it
        "R": "#4a3426",  # dark rim of the facial disc
        "M": "#8f6a48",  # brown: head, back and wing coverts
        "D": "#5e4330",  # dark brown: streaks, flight feathers and tail
        "S": "#f3ead8",  # pale spots: the row on the shoulder, the bars on the flight feathers
        "L": "#e9dcc4",  # pale buff belly
        "T": "#b08a63",  # streaks on the belly
        "P": "#a9ae96",  # gray-green beak
        "Q": "#7d826c",  # tip of the beak
        "N": "#1a1210",  # pupil
        EYE: "#f5c518",  # yellow eye, above and below the pupil
        EYE_SHINE: "#f5c518",  # yellow eye beside the pupil: dark while blinking
        "F": "#b5a690",  # toes
        "G": "#8f826e",  # far toes
    },
    animations={
        # Soon after it stops, it turns its head to look at you for 2 s, then back in profile.
        Activity.STANDING: Animation((STAND_A, *(STAND_B,) * 4, *(STAND_A,) * 9), fps=2),
        Activity.WALKING: Animation((FLY_0, FLY_1, FLY_2, FLY_1), fps=10),  # it flies around
        Activity.SITTING: Animation((REST_A, REST_B), fps=1),  # dozing, its head sinking
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=8),  # flapping, its legs dangling
    },
    # It rests 3 to 7 s between flights, long enough to look at you (and only once).
    gait=Gait(speed=70, max_slope=1.0, distance=(120, 420), rest=(3.0, 7.0)),
    locomotion=Locomotion.FLY,
    sit_label=QT_TRANSLATE_NOOP("PetWindow", "Rest"),
)
