"""The penguin: a gentoo, black and white with an orange bill and feet, that waddles around."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ..............KDDDDDDDBBDDKKK...
    ..............KDDDDDDDDDDDK.....
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDDDDKKKLBBBBBK....
    ............KDDDDKSSKLBBBBBBK...
    ............KDDDKSSSKLBBBBBBK...
    ...........KDDDDKSSKLBBBBBBBK...
    ...........KDDDDKSSKLBBBBBBBK...
    ...........KDDDDKSKLBBBBBBBBK...
    .........KKDDDDDKKLBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ...............KGGKFFFFFFK......
    ...............KK.KKKKKK........
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ..............KDDDDDDDBBDDKKK...
    ..............KDDDDDDDDDDDK.....
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDKKKKKKLBBBBBK....
    .........KKKKSSSSSSKLBBBBBBBK...
    ........KSSSSSSKKKLBBBBBBBBBK...
    ........KKKKKKKDLBBBBBBBBBBBK...
    ...........KDDDDLBBBBBBBBBBBK...
    ...........KDDDDLBBBBBBBBBBBK...
    .........KKDDDDDLBBBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ...............KGGKFFFFFFK......
    ...............KK.KKKKKK........
    ................................
""")

WALK_0 = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ..............KDDDDDDDBBDDKKK...
    ..............KDDDDDDDDDDDK.....
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDDDKKKKLBBBBBK....
    ............KDDDKSSSKLBBBBBBK...
    ............KDDKSSSKLBBBBBBBK...
    ...........KDDKSSSKLBBBBBBBBK...
    ...........KDKSSSKLBBBBBBBBBK...
    ...........KKSSKKLBBBBBBBBBBK...
    .........KKDKKKLBBBBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ............KGGGK..KFFFFFFK.....
    ............KKKK...KKKKKKK......
    ................................
""")

WALK_1 = art("""
    ................................
    ................................
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ..............KDDDDDDDBBDDKKK...
    ..............KDDDDDDDDDDDK.....
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDDDKKKKLBBBBBK....
    ............KDDDKSSSKLBBBBBBK...
    ............KDDKSSSKLBBBBBBBK...
    ...........KDDKSSSKLBBBBBBBBK...
    ...........KDKSSSKLBBBBBBBBBK...
    ...........KKSSKKLBBBBBBBBBBK...
    .........KKDKKKLBBBBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ...............KGKKFFK..........
    ...............KGGKFFFFFFK......
    ...............KK.KKKKKK........
    ................................
""")

WALK_2 = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ..............KDDDDDDDBBDDKKK...
    ..............KDDDDDDDDDDDK.....
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDDDKKKKLBBBBBK....
    ............KDDDKSSSKLBBBBBBK...
    ............KDDKSSSKLBBBBBBBK...
    ...........KDDKSSSKLBBBBBBBBK...
    ...........KDKSSSKLBBBBBBBBBK...
    ...........KKSSKKLBBBBBBBBBBK...
    .........KKDKKKLBBBBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ............KFFFFFKGGGGK........
    .............KKKKK.KKKK.........
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .................KKKKK..........
    ...............KKSBBDDKK........
    ..............KSSDDBBBDDK.......
    .............KSDDDDDBBBBDKKK....
    .............KSDDDDDBEEBDOOOOK..
    .............KSDDDDDBNHBDOOOK...
    .............KDDDDDDDBBDDKKK....
    .............KDDDDDDDDDDDK......
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDDDDKKKLBBBBBK....
    ............KDDDDKSSKLBBBBBBK...
    ............KDDDKSSSKLBBBBBBK...
    ...........KDDDDKSSKLBBBBBBBBK..
    ...........KDDDDKSSKLBBBBBBBBK..
    ...........KDDDDKSKLBBBBBBBBBK..
    .........KKDDDDDKKLBBBBBBBBBKGGK
    ........KDDDDDLLLLBBBBBBBBLKFFFK
    .........KKKKKKKKKKKKKKKKKKKKKK.
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .................KKKKK..........
    ...............KKSBBDDKK........
    ..............KSSDDBBBDDK.......
    .............KSDDDDDBBBBDKKK....
    .............KSDDDDDBEEBDOOOOK..
    .............KSDDDDDBNHBDOOOK...
    .............KDDDDDDDBBDDKKK....
    .............KDDDDDDDDDDDDK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDDDDKKKLBBBBBK....
    ............KDDDDKSSKLBBBBBBK...
    ............KDDDKSSSKLBBBBBBK...
    ...........KDDDDKSSKLBBBBBBBBK..
    ...........KDDDDKSSKLBBBBBBBBK..
    ...........KDDDDKSKLBBBBBBBBBK..
    .........KKDDDDDKKLBBBBBBBBBKGGK
    ........KDDDDDLLLLBBBBBBBBLKFFFK
    .........KKKKKKKKKKKKKKKKKKKKKK.
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ..............KDDDDDDDBBDDKKK...
    ..............KDDDDDDDDDDDK.....
    .............KDDDDDDDDDDDBK.....
    .............KDDDDDDDDDBBBBK....
    ............KDDKKKKKKLBBBBBK....
    .........KKKKSSSSSSKLBBBBBBBK...
    ........KSSSSSSKKKLBBBBBBBBBK...
    ........KKKKKKKDLBBBBBBBBBBBK...
    ...........KDDDDLBBBBBBBBBBBK...
    ...........KDDDDLBBBBBBBBBBBK...
    .........KKDDDDDLBBBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ...............KGK.KFFK.........
    ...............KGGKKFFFK........
    ................KKK.KKKK........
    ................................
    ................................
    ................................
""")

CARRIED_B = art("""
    ................................
    ................................
    ..................KKKKK.........
    ................KKSBBDDKK.......
    ...............KSSDDBBBDDK......
    ..............KSDDDDDBBBBDKKK...
    ..............KSDDDDDBEEBDOOOOK.
    ..............KSDDDDDBNHBDOOOK..
    ........KKK...KDDDDDDDBBDDKKK...
    .......KSSKKK.KDDDDDDDDDDDK.....
    .......KSSSSSKKDDDDDDDDDDBK.....
    ........KKSSSSSKKDDDDDDBBBBK....
    ..........KKSSSSSKKDDLBBBBBK....
    ............KKKSSSKDDLBBBBBBK...
    ............KDDKKKDDLBBBBBBBK...
    ...........KDDDDDDDLBBBBBBBBK...
    ...........KDDDDDDLBBBBBBBBBK...
    ...........KDDDDDLBBBBBBBBBBK...
    .........KKDDDDDLBBBBBBBBBBK....
    ........KDDDDDLLLLBBBBBBBLK.....
    .........KKKKKKKKKKKKKKKKK......
    ...............KGK.KFFK.........
    ...............KGGKKFFFK........
    ................KKK.KKKK........
    ................................
    ................................
    ................................
""")

PENGUIN = Species(
    key="penguin",
    label="Penguin",
    palette={
        "K": "#1a1d27",  # outline
        "B": "#f6f6f1",  # white feathers: belly and the band over the eye, which frames it
        "L": "#d3d9e3",  # shade on the white feathers
        "D": "#323a4b",  # black feathers
        "S": "#48526a",  # sheen on the black feathers, flipper
        "O": "#f06a2d",  # orange-red bill
        "F": "#f59a4a",  # feet
        "G": "#cf7433",  # far foot
        "N": "#0f1117",  # pupil
        EYE: "#0f1117",
        EYE_SHINE: "#ffffff",
    },
    animations={
        # Flapping its flipper now and then.
        Activity.STANDING: Animation((STAND_A, STAND_A, STAND_A, STAND_B, STAND_A, STAND_B), fps=3),
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_1), fps=8),  # waddling
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # sitting back on its tail, nodding off
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=8),  # flapping its flippers
    },
    gait=Gait(speed=30, max_slope=0.4, distance=(60, 240)),
)
