"""The rabbit: a white bunny with pink ears that hops around and sits up to sniff the air."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, Frame, art

STAND_A = art("""
    ................................
    ................KK....KK........
    ...............KBBK..KDDK.......
    ...............KBPBK.KDDK.......
    ...............KBPBK.KDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    .................KBPBKDDK.......
    .................KBBBKDK........
    ................KKBBBBKKKK......
    .........KKKKK.KBBBBBBBBBBKK....
    .......KKBBBBBKDBBBBBBBBEEBBK...
    ......KBBBBBBBBDBBBBBBBBEEBBBK..
    .....KBBBBBBBBBDBBBBBBBBNHBBBK..
    ..KKKBBBBBBBBBBDBBBBBBBBBBBBPK..
    .KWWWKBBBBBBBBBBDBBBBBBBBBBWNK..
    KWWWWKBBBBBBBBBBBKBBBBBBBWWWK...
    KWWWWKBBBBBBBBBBBBKKBBBBWWKK....
    .KWWKBBBBBBBBBBBBBBKKKKKKK......
    ..KKBBBBBBBBBBBBBBBBBBBK........
    ..KBBBBBBBBBBBBBBBBKBBBK........
    ..KBBBBBDDDDDDDBBBBKBBBK........
    ...KBBDDBBBBBBBDDBBKBBBK........
    ...KBBBBBBBBBBBBBWWKWWWK........
    ....KKKKKKKKKKKKKKKKKKK.........
    ................................
""")

STAND_B = art("""
    ................................
    ................KK....KK........
    ...............KBBK..KDDK.......
    ...............KBPBK.KDDK.......
    ...............KBPBK.KDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    .................KBPBKDDK.......
    .................KBBBKDK........
    ................KKBBBBKKKK......
    .........KKKKK.KBBBBBBBBBBKK....
    .......KKBBBBBKDBBBBBBBBEEBBK...
    ......KBBBBBBBBDBBBBBBBBEEBBBK..
    .....KBBBBBBBBBDBBBBBBBBNHBBPK..
    ..KKKBBBBBBBBBBDBBBBBBBBBBBBBK..
    .KWWWKBBBBBBBBBBDBBBBBBBBBBWNK..
    KWWWWKBBBBBBBBBBBKBBBBBBBWWWK...
    KWWWWKBBBBBBBBBBBBKKBBBBWWKK....
    .KWWKBBBBBBBBBBBBBBKKKKKKK......
    ..KKBBBBBBBBBBBBBBBBBBBK........
    ..KBBBBBBBBBBBBBBBBKBBBK........
    ..KBBBBBDDDDDDDBBBBKBBBK........
    ...KBBDDBBBBBBBDDBBKBBBK........
    ...KBBBBBBBBBBBBBWWKWWWK........
    ....KKKKKKKKKKKKKKKKKKK.........
    ................................
""")

STAND_C = art("""
    ................................
    ................KK.....KK.......
    ...............KBBK...KDDK......
    ...............KBPBK..KDDK......
    ...............KBPBK.KDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    .................KBPBKDDK.......
    .................KBBBKDK........
    ................KKBBBBKKKK......
    .........KKKKK.KBBBBBBBBBBKK....
    .......KKBBBBBKDBBBBBBBBEEBBK...
    ......KBBBBBBBBDBBBBBBBBEEBBBK..
    .....KBBBBBBBBBDBBBBBBBBNHBBBK..
    ..KKKBBBBBBBBBBDBBBBBBBBBBBBPK..
    .KWWWKBBBBBBBBBBDBBBBBBBBBBWNK..
    KWWWWKBBBBBBBBBBBKBBBBBBBWWWK...
    KWWWWKBBBBBBBBBBBBKKBBBBWWKK....
    .KWWKBBBBBBBBBBBBBBKKKKKKK......
    ..KKBBBBBBBBBBBBBBBBBBBK........
    ..KBBBBBBBBBBBBBBBBKBBBK........
    ..KBBBBBDDDDDDDBBBBKBBBK........
    ...KBBDDBBBBBBBDDBBKBBBK........
    ...KBBBBBBBBBBBBBWWKWWWK........
    ....KKKKKKKKKKKKKKKKKKK.........
    ................................
""")

HOP_REACH = art("""
    .................KK....KK.......
    ................KBBK..KDDK......
    ................KBPBK.KDDK......
    ................KBPBK.KDDK......
    .................KBPBKKDDK......
    .................KBPBKKDDK......
    .................KBPBKKDDK......
    ..................KBPBKDDK......
    ..................KBBBKDK.......
    .................KKBBBBKKKK.....
    ...........KKKK.KBBBBBBBBBBKK...
    ........KKKBBBBKDBBBBBBBBEEBBK..
    ......KKBBBBBBBBDBBBBBBBBEEBBBK.
    .....KBBBBBBBBBBDBBBBBBBBNHBBBK.
    ....KBBBBBBBBBBBDBBBBBBBBBBBBPK.
    ..KKKBBBBBBBBBBBBDBBBBBBBBBBWNK.
    .KWWWKBBBBBBBBBBBBKBBBBBBBWWWK..
    KWWWWKBBBBBBBBBBBBBKKBBBBWWKK...
    KWWWWKBBBBBBBBBBBBBBKKKKKKK.....
    .KWWKBBBBBBBBBBBBBBBBBBBK.......
    ..KKBBBBBBBBBBBBBBBBKBBBK.......
    ..KBBBBBBBBBBBBBKKKKKKBBBK......
    ..KBBBBBDDDDDDDKKKK...KWWWK.....
    ...KBBDDBBBBBBBDDBBK...KKK......
    ...KBBBBBBBBBBBBBWWK............
    ....KKKKKKKKKKKKKKK.............
    ................................
""")

HOP_ARCH = art("""
    ................................
    ..................KK....KK......
    .................KBBK..KDDK.....
    .................KBPBK.KDDK.....
    .................KBPBK.KDDK.....
    ..................KBPBKKDDK.....
    ..................KBPBKKDDK.....
    ........KKK.......KBPBKKDDK.....
    .KKK.KKKBBBKKKK....KBPBKDDK.....
    KWWWKBBBBBBBBBBKK..KBBBKDK......
    KWWWKBBBBBBBBBBBBKKKBBBBKKKK....
    KWWWKBBBBBBBBBBBBKBBBBBBBBBBKK..
    .KKKKBBBBBBBBBBBBDBBBBBBBBEEBBK.
    .....KBBBBBBBBBBBDBBBBBBBBEEBBBK
    .....KBBBBBBBBBBBDBBBBBBBBNHBBBK
    ......KBBBBBBBBBBDBBBBBBBBBBBBPK
    .......KBBBBBBBBBBDBBBBBBBBBBWNK
    ........KKBBBBBBBBBKBBBBBBBWWWK.
    .......KKKKKKKKBBBBBKKBBBBWWKK..
    ......KBBBBBBBBKKBBBBBKKKKKK....
    .....KBBBBBBBBWWKKKKKBBBK.......
    ......KKKKKKKKKK.KDDKBBBK.......
    .................KDDKBBBK.......
    .................KDDKBBBK.......
    .................KDDKWWWK.......
    .................KKKKKKKK.......
    ................................
""")

SIT_A = art("""
    ..............KK....KK..........
    .............KBBK..KDDK.........
    .............KBPBK.KDDK.........
    .............KBPBK.KDDK.........
    ..............KBPBKKDDK.........
    ..............KBPBKKDDK.........
    ..............KBPBKKDDK.........
    ...............KBPBKDDK.........
    ...............KBBBKDK..........
    ..............KKBBBBKKKK........
    .............KBBBBBBBBBBKK......
    .............KBBBBBBBBEEBBK.....
    .............KBBBBBBBBEEBBBK....
    .............KBBBBBBBBNHBBBK....
    ............KDBBBBBBBBBBBBPK....
    ...........KBBDBBBBBBBBBBWNK....
    ..........KBBBBKBBBBBBBWWWK.....
    ..........KBBBBBKKBBBBWWKK......
    .........KBBBBBBBKKKKKKK........
    .........KBBBBBBBBBBBKBBK.......
    .....KKKKBBBBBBBBBBBBKWWK.......
    ....KWWWKBBBBBBBBDBBBBKK........
    ....KWWWKBBBBBBBBBDBBBBK........
    ....KWWWKBBBBBBBBBDBBBBBK.......
    .....KKKBBBBBBBBBDBBBBWWWK......
    ........KKKKKKKKKKKKKKKKK.......
    ................................
""")

SIT_B = art("""
    ..............KK....KK..........
    .............KBBK..KDDK.........
    .............KBPBK.KDDK.........
    .............KBPBK.KDDK.........
    ..............KBPBKKDDK.........
    ..............KBPBKKDDK.........
    ..............KBPBKKDDK.........
    ...............KBPBKDDK.........
    ...............KBBBKDK..........
    ..............KKBBBBKKKK........
    .............KBBBBBBBBBBKK......
    .............KBBBBBBBBEEBBK.....
    .............KBBBBBBBBEEBBBK....
    .............KBBBBBBBBNHBBPK....
    ............KDBBBBBBBBBBBBBK....
    ...........KBBDBBBBBBBBBBWNK....
    ..........KBBBBKBBBBBBBWWWK.....
    ..........KBBBBBKKBBBBWWKK......
    .........KBBBBBBBKKKKKKK........
    .........KBBBBBBBBBBBKBBK.......
    .....KKKKBBBBBBBBBBBBKWWK.......
    ....KWWWKBBBBBBBBDBBBBKK........
    ....KWWWKBBBBBBBBBDBBBBK........
    ....KWWWKBBBBBBBBBDBBBBBK.......
    .....KKKBBBBBBBBBDBBBBWWWK......
    ........KKKKKKKKKKKKKKKKK.......
    ................................
""")

CARRIED_A = art("""
    ................................
    ................KK....KK........
    ...............KBBK..KDDK.......
    ...............KBPBK.KDDK.......
    ...............KBPBK.KDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    .................KBPBKDDK.......
    .................KBBBKDK........
    ................KKBBBBKKKK......
    .........KKKKK.KBBBBBBBBBBKK....
    .......KKBBBBBKDBBBBBBBBEEBBK...
    ......KBBBBBBBBDBBBBBBBBEEBBBK..
    .....KBBBBBBBBBDBBBBBBBBNHBBBK..
    ..KKKBBBBBBBBBBDBBBBBBBBBBBBPK..
    .KWWWKBBBBBBBBBBDBBBBBBBBBBWNK..
    KWWWWKBBBBBBBBBBBKBBBBBBBWWWK...
    KWWWWKBBBBBBBBBBBBKKBBBBWWKK....
    .KWWKBBBBBBBBBBBBBBKKKKKKK......
    ..KKBBBBBBBBBBBBBBBBBBBK........
    ..KBBBBBBBBBBBBBBBBKBBBK........
    ...KBBBBBDBBBBBBBBBKBBBK........
    ....KBBBBBDKKKKKKKKKBBBK........
    .....KBBBBK........KBBBK........
    .....KWWWK.........KWWWK........
    ......KKK...........KKK.........
""")

CARRIED_B = art("""
    ................................
    ................KK....KK........
    ...............KBBK..KDDK.......
    ...............KBPBK.KDDK.......
    ...............KBPBK.KDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    ................KBPBKKDDK.......
    .................KBPBKDDK.......
    .................KBBBKDK........
    ................KKBBBBKKKK......
    .........KKKKK.KBBBBBBBBBBKK....
    .......KKBBBBBKDBBBBBBBBEEBBK...
    ......KBBBBBBBBDBBBBBBBBEEBBBK..
    .....KBBBBBBBBBDBBBBBBBBNHBBBK..
    ..KKKBBBBBBBBBBDBBBBBBBBBBBBPK..
    .KWWWKBBBBBBBBBBDBBBBBBBBBBWNK..
    KWWWWKBBBBBBBBBBBKBBBBBBBWWWK...
    KWWWWKBBBBBBBBBBBBKKBBBBWWKK....
    .KWWKBBBBBBBBBBBBBBKKKKKKK......
    ..KKBBBBBBBBBBBBBBBBBBBK........
    ..KBBBBBBBBBBBBBBBBBKBBBK.......
    ..KBBBBBBDBBBBBBBBBBKBBBK.......
    .KBBBBBDKKKKKKKKKKKKKBBBK.......
    KBBBBKK.............KWWWK.......
    KWWKK................KKK........
    .KK.............................
""")


def sniffing(still: Frame, twitch: Frame) -> tuple[Frame, ...]:
    """A burst of nose twitches: twitch, twitch, pause."""
    return (still, twitch, still, twitch, still, still)


RABBIT = Species(
    key="rabbit",
    label=QT_TRANSLATE_NOOP("Species", "Rabbit"),
    palette={
        "K": "#4a3f3c",  # outline
        "B": "#f2eee6",  # white fur
        "D": "#cfc5b6",  # shade: far ear and front leg, the back of the head, the haunch
        "W": "#ffffff",  # snow white: cottontail, muzzle, paws
        "P": "#f0a0a8",  # inner ear, nose
        "N": "#1e1512",  # mouth, pupil
        EYE: "#1e1512",
        EYE_SHINE: "#ffffff",
    },
    animations={
        # Twitching its nose in bursts, and now and then turning an ear.
        Activity.STANDING: Animation(
            (*sniffing(STAND_A, STAND_B), STAND_A, STAND_A, STAND_C, STAND_C, STAND_A, STAND_A),
            fps=4,
        ),
        # Hopping: crouched, pushing off with its front paws up, landing with its rump up.
        Activity.WALKING: Animation((STAND_A, HOP_REACH, HOP_ARCH), fps=6),
        # Sitting up on its haunches, sniffing the air.
        Activity.SITTING: Animation((*sniffing(SIT_A, SIT_B), SIT_A, SIT_A), fps=4),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),  # kicking
    },
    gait=Gait(speed=45, max_slope=0.4, distance=(80, 320)),
    locomotion=Locomotion.HOP,
)
