"""The snail: a garden snail that crawls around and retreats into its shell to rest."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ............................KK..
    .....................KK....KEEK.
    ....................KEEK...KNHK.
    ..........KKKKKK....KNHK...KBK..
    ........KKTTSSSSKK..KDK...KBK...
    .......KTTSSSSSSSSK..KDK..KBK...
    ......KTSSSRRRRRSSSK.KDK..KBK...
    ......KTSSRTTTTSRSSK..KDKKBK....
    .....KSSSRTTSSSTTRSSK.KDKKBK....
    .....KSSSRTSSSSSSTRSK..KDKBK....
    .....KSSSRTSTRRSSTRSK..KDKBK....
    .....KSSSRTTSTRSSTRUK..KDKBK....
    .....KSSSSRTTTRSTTRUK.KKDKBKK...
    ......KSTSSRRRSTSRUKKKWWWWWBBK..
    ......KRSTTSSSSTRUUKDBBWWWBBBBK.
    .......KRRRTTTTRUUKDDBBBBBBBBNK.
    ........KKSRRRRUKKDDBBBBBBBBBK..
    ..KKKKKKBBKKKKKKDDBBBBBBBBBBBBK.
    .KWWWWBBBBBBBBBBBBBBBBBBBBBBBBK.
    KDDDDDDDDDDDDDDDDDDDDDDDDDDDDDK.
    .KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..
    ................................
""")

STAND_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    .............................KK.
    ......................KK....KEEK
    .....................KEEK...KNHK
    ..........KKKKKK.....KNHK...KBK.
    ........KKTTSSSSKK...KDK...KBK..
    .......KTTSSSSSSSSK..KDK...KBK..
    ......KTSSSRRRRRSSSK..KDK.KBK...
    ......KTSSRTTTTSRSSK..KDK.KBK...
    .....KSSSRTTSSSTTRSSK.KDKKBK....
    .....KSSSRTSSSSSSTRSK..KDKBK....
    .....KSSSRTSTRRSSTRSK..KDKBK....
    .....KSSSRTTSTRSSTRUK..KDKBK....
    .....KSSSSRTTTRSTTRUK.KKDKBKK...
    ......KSTSSRRRSTSRUKKKWWWWWBBK..
    ......KRSTTSSSSTRUUKDBBWWWBBBBK.
    .......KRRRTTTTRUUKDDBBBBBBBBNK.
    ........KKSRRRRUKKDDBBBBBBBBBK..
    ..KKKKKKBBKKKKKKDDBBBBBBBBBBBBK.
    .KWWWWBBBBBBBBBBBBBBBBBBBBBBBBK.
    KDDDDDDDDDDDDDDDDDDDDDDDDDDDDDK.
    .KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..
    ................................
""")

STAND_C = art("""
    ................................
    ................................
    ................................
    ................................
    ...........................KK...
    ..........................KEEK..
    ....................KK....KNHK..
    ...................KEEK...KBK...
    ..........KKKKKK...KNHK...KBK...
    ........KKTTSSSSKK.KDK....KBK...
    .......KTTSSSSSSSSK.KDK...KBK...
    ......KTSSSRRRRRSSSKKDK...KBK...
    ......KTSSRTTTTSRSSK.KDK.KBK....
    .....KSSSRTTSSSTTRSSK.KDKKBK....
    .....KSSSRTSSSSSSTRSK..KDKBK....
    .....KSSSRTSTRRSSTRSK..KDKBK....
    .....KSSSRTTSTRSSTRUK..KDKBK....
    .....KSSSSRTTTRSTTRUK.KKDKBKK...
    ......KSTSSRRRSTSRUKKKWWWWWBBK..
    ......KRSTTSSSSTRUUKDBBWWWBBBBK.
    .......KRRRTTTTRUUKDDBBBBBBBBNK.
    ........KKSRRRRUKKDDBBBBBBBBBK..
    ..KKKKKKBBKKKKKKDDBBBBBBBBBBBBK.
    .KWWWWBBBBBBBBBBBBBBBBBBBBBBBBK.
    KDDDDDDDDDDDDDDDDDDDDDDDDDDDDDK.
    .KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..
    ................................
""")

CRAWL_STRETCH = art("""
    ................................
    ................................
    ................................
    ................................
    ............................KK..
    ...........................KEEK.
    .....................KK....KNHK.
    ....................KEEK...KBK..
    ..........KKKKKK....KNHK...KBK..
    ........KKTTSSSSKK..KDK....KBK..
    .......KTTSSSSSSSSK..KDK...KBK..
    ......KTSSSRRRRRSSSK.KDK...KBK..
    ......KTSSRTTTTSRSSK..KDK.KBK...
    .....KSSSRTTSSSTTRSSK..KDKKBK...
    .....KSSSRTSSSSSSTRSK...KDKBK...
    .....KSSSRTSTRRSSTRSK...KDKBK...
    .....KSSSRTTSTRSSTRUK...KDKBK...
    .....KSSSSRTTTRSTTRUK..KKDKBKK..
    ......KSTSSRRRSTSRUKKKKWWWWWBBK.
    ......KRSTTSSSSTRUUKDBBBWWWBBBBK
    .......KRRRTTTTRUUKDDBBBBBBBBBNK
    ........KKSRRRRUKKDDBBBBBBBBBBK.
    ..KKKKKKBBKKKKKKDDBBBBBBBBBBBBBK
    .KWWWWBBBBBBBBBBBBBBBBBBBBBBBBBK
    KDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDK
    .KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..........KKKKKK................
    ........KKTTSSSSKK..............
    .......KTTSSSSSSSSK.............
    ......KTSSSRRRRRSSSK............
    ......KTSSRTTTTSRSSK............
    .....KSSSRTTSSSTTRSSK...........
    .....KSSSRTSSSSSSTRSK...........
    .....KSSSRTSTRRSSTRSK...........
    .....KSSSRTTSTRSSTKKK...........
    .....KSSSSRTTTRSTKNNNNK.........
    ......KSTSSRRRSTKEENEETK........
    ......KRSTTSSSSKNHHNHHTK........
    .......KRRRTTTTKNNNNNNTK........
    ........KKSRRRRKTTTTTTK.........
    ..........KKKKKKKKKKKK..........
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..........KKKKKK................
    ........KKTTSSSSKK..............
    .......KTTSSSSSSSSK.............
    ......KTSSSRRRRRSSSK............
    ......KTSSRTTTTSRSSK............
    .....KSSSRTTSSSTTRSSK...........
    .....KSSSRTSSSSSSTRSK...........
    .....KSSSRTSTRRSSTRSK...........
    .....KSSSRTTSTRSSTKKK...........
    .....KSSSSRTTTRSTKNNNNK.........
    ......KSTSSRRRSTKEENEETK........
    ......KRSTTSSSSKNHNNHNTK........
    .......KRRRTTTTKNNNNNNTK........
    ........KKSRRRRKTTTTTTK.........
    ..........KKKKKKKKKKKK..........
    ................................
""")

SIT_C = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..........KKKKKK................
    ........KKTTSSSSKK..............
    .......KTTSSSSSSSSK.............
    ......KTSSSRRRRRSSSK............
    ......KTSSRTTTTSRSSK............
    .....KSSSRTTSSSTTRSSK...........
    .....KSSSRTSSSSSSTRSK...........
    .....KSSSRTSTRRSSTRSK...........
    .....KSSSRTTSTRSSTKKK...........
    .....KSSSSRTTTRSTKNNNNK.........
    ......KSTSSRRRSTKEENEETK........
    ......KRSTTSSSSKNNHNNHTK........
    .......KRRRTTTTKNNNNNNTK........
    ........KKSRRRRKTTTTTTK.........
    ..........KKKKKKKKKKKK..........
    ................................
""")

SNAIL = Species(
    key="snail",
    label=QT_TRANSLATE_NOOP("Species", "Snail"),
    palette={
        "K": "#3b2a1f",  # outline
        "B": "#cdbfa6",  # grayish beige body
        "D": "#a8987e",  # shade: far eye stalk, where the body goes into the shell, the sole
        "W": "#e9e0cf",  # light on the head and the tail
        "S": "#c98a4a",  # caramel shell
        "T": "#eab87a",  # light ridges of the shell, its lip
        "R": "#8a5530",  # spiral groove
        "U": "#a86a36",  # shadow on the shell's lower side
        "N": "#1e1510",  # mouth, pupil, the dark inside of the shell
        EYE: "#1e1510",
        EYE_SHINE: "#ffffff",
    },
    animations={
        # Looking around: the eye stalks lean ahead, then back.
        Activity.STANDING: Animation(
            (STAND_A, STAND_A, STAND_B, STAND_B, STAND_A, STAND_A, STAND_C, STAND_C), fps=2
        ),
        # Crawling: the shell and the tail glide along while the head stretches ahead, its eye
        # stalks straightening up, and draws back.
        Activity.WALKING: Animation((STAND_A, CRAWL_STRETCH), fps=2.5),
        # In its shell, peeking out of the dark and looking around now and then.
        Activity.SITTING: Animation((SIT_A, SIT_A, SIT_A, SIT_B, SIT_A, SIT_A, SIT_C), fps=1),
        # Picked up, it hides in its shell, its eyes darting back and forth.
        Activity.CARRIED: Animation((SIT_B, SIT_C), fps=3),
    },
    gait=Gait(speed=15, max_slope=0.4, distance=(60, 200)),
    locomotion=Locomotion.CRAWL,
    sit_label=QT_TRANSLATE_NOOP("PetWindow", "Retreat into shell"),
)
