"""The sea turtle: it swims around and rests on the bottom when told to sit."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Locomotion, Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

FLOAT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK................
    ......KKKSDTTTDSKK..............
    ....KKSTTDTTTTSDTSK.....KKKKK...
    ..KKSTTTDSTTTSSDTTSK..KKBGBGBK..
    .KSTTSSDSSSSSSSSDSTSKKBGBBBBBBK.
    .KSSSSDSSSSSSSSSSDSSSKBBBBBEEBK.
    KKKKRRDRRDRRDRRDRRDRRKBBBBBNHBBK
    KBBBKYYYYYYYYYYKKKKKKBBBBBBBBBNK
    KBBKKKKKKKKKKKKBBBBBKWWWWWWWWNK.
    KKK........KKBBBBBBKKKKKKKKKKK..
    .........KKBBBBBBBK.............
    ........KBBBBBBBGK..............
    .......KBBBBBGGKK...............
    ......KBBGGKKK..................
    ......KKKK......................
    ................................
    ................................
    ................................
""")

FLOAT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK................
    ......KKKSDTTTDSKK..............
    ....KKSTTDTTTTSDTSK.....KKKKK...
    ..KKSTTTDSTTTSSDTTSK..KKBGBGBK..
    .KSTTSSDSSSSSSSSDSTSKKBGBBBBBBK.
    .KSSSSDSSSSSSSSSSDSSSKBBBBBEEBK.
    KKKKRRDRRDRRDRRDRRDRRKBBBBBNHBBK
    KBBBKYYYYYYYYYYKKKKKKBBBBBBBBBNK
    KBBKKKKKKKKKKKKBBBBBKWWWWWWWWNK.
    KKK......KKKBBBBBBBBKKKKKKKKKK..
    .......KKBBBBBBBBBBK............
    ......KBBBBBBBBGGKK.............
    .....KBBBGGGGKKK................
    .....KKKK.......................
    ................................
    ................................
    ................................
    ................................
""")

SWIM_UP = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ......KKK.......................
    ......KWBKK.....................
    .......KWBBKK...................
    ........KWBBBKK.................
    .........KWBBBBKK...............
    ......KKKKKWBBBBBK..............
    ....KKSTTDTKWBBBBBK.....KKKKK...
    ..KKSTTTDSTTKWBBBBBK..KKBGBGBK..
    .KSTTSSDSSSSSKWBBBBKKKBGBBBBBBK.
    .KSSSSDSSSSSSSKWBBBBKKBBBBBEEBK.
    KKKKRRDRRDRRDRRKBBBBKKBBBBBNHBBK
    KBBBKYYYYYYYYYYYKKKKKBBBBBBBBBNK
    KBBKKKKKKKKKKKKKKKK.KWWWWWWWWNK.
    KKK.................KKKKKKKKKK..
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
""")

SWIM_DOWN = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK................
    ......KKKSDTTTDSKK..............
    ....KKSTTDTTTTSDTSK.....KKKKK...
    ..KKSTTTDSTTTSSDTTSK..KKBGBGBK..
    .KSTTSSDSSSSSSSSDSTSKKBGBBBBBBK.
    .KSSSSDSSSSSSSSSSDSSSKBBBBBEEBK.
    KKKKRRDRRDRRDRRDRRDRRKBBBBBNHBBK
    KBBBKYYYYYYYYYYKKKKKKBBBBBBBBBNK
    KBBKKKKKKKKKKKKBBBBBWKWWWWWWWNK.
    KKK..........KBBBBBWKKKKKKKKKK..
    ............KBBBBWK.............
    ............KBBBWK..............
    ...........KBBBWK...............
    ...........KBBWK................
    ..........KBBWK.................
    ..........KBWK..................
    ..........KKK...................
    ................................
    ................................
""")

SIT_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK................
    ......KKKSDTTTDSKK......KKKKK...
    ....KKSTTDTTTTSDTSK...KKBGBGBK..
    ..KKSTTTDSTTTSSDTTSK.KBGBBBBBBK.
    .KSTTSSDSSSSSSSSDSTSKKBBBBBEEBK.
    .KSSSSDSSSSSSSSKKKKKKKBBBBBNHBBK
    KRRDRRDRRDRKKKKBBBBBKBBBBBBBBBNK
    KBBBKYYYKKKBBBBBBBGGKWWWWWWWWNK.
    .KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..
    ................................
""")

SIT_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK........KKKKK...
    ......KKKSDTTTDSKK....KKBGBGBK..
    ....KKSTTDTTTTSDTSK..KBGBBBBBBK.
    ..KKSTTTDSTTTSSDTTSK.KBBBBBEEBK.
    .KSTTSSDSSSSSSSSDSTSKKBBBBBNHBBK
    .KSSSSDSSSSSSSSKKKKKKBBBBBBBBBNK
    KRRDRRDRRDRKKKKBBBBBKWWWWWWWWNK.
    KBBBKYYYKKKBBBBBBBGGKKKKKKKKKK..
    .KKKKKKKKKKKKKKKKKKK............
    ................................
""")

CARRIED_A = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ......KKK.......................
    ......KWBKK.....................
    .......KWBBKK...................
    ........KWBBBKK.................
    .........KWBBBBKK...............
    ......KKKKKWBBBBBK......KKKKK...
    ....KKSTTDTKWBBBBBK...KKBGBGBK..
    ..KKSTTTDSTTKWBBBBBK.KBGBBBBBBK.
    KKSTTSSDSSSSSKWBBBBKKKBBBBBEEBK.
    KBKKSSDSSSSSSSKWBBBBKKBBBBBNHBBK
    KBBBKRDRRDRRDRRKBBBBKBBBBBBBBBNK
    .KKKYYYYYYYYYYYYKKKKKWWWWWWWWNK.
    ..KKKKKKKKKKKKKKKKK.KKKKKKKKKK..
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
""")

CARRIED_B = art("""
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .........KKKKKKK................
    ......KKKSDTTTDSKK......KKKKK...
    ....KKSTTDTTTTSDTSK...KKBGBGBK..
    ..KKSTTTDSTTTSSDTTSK.KBGBBBBBBK.
    .KSTTSSDSSSSSSSSDSTSKKBBBBBEEBK.
    .KSSSSDSSSSSSSSSSDSSSKBBBBBNHBBK
    KKKKRRDRRDRRDRRDRRDRKBBBBBBBBBNK
    KBBBKYYYYYYYYYYKKKKKKWWWWWWWWNK.
    KBBKKKKKKKKKKKKBBBBBWKKKKKKKKK..
    KKK..........KBBBBBWK...........
    ............KBBBBWK.............
    ............KBBBWK..............
    ...........KBBBWK...............
    ...........KBBWK................
    ..........KBBWK.................
    ..........KBWK..................
    ..........KKK...................
    ................................
    ................................
""")

TURTLE = Species(
    key="turtle",
    label=QT_TRANSLATE_NOOP("Species", "Sea Turtle"),
    palette={
        "K": "#233026",  # outline
        "B": "#6fa582",  # skin
        "G": "#4d7a5e",  # scales on the head and flippers
        "W": "#cfe3b0",  # pale flipper edges, jaw
        "S": "#8d6a3b",  # shell
        "T": "#b89050",  # light middle of the shell's plates
        "D": "#63482a",  # seams between the plates
        "R": "#a98249",  # shell rim
        "Y": "#f0e2a6",  # belly shell
        "N": "#15201a",  # pupil, mouth
        EYE: "#15201a",
        EYE_SHINE: "#ffffff",
    },
    animations={
        # It floats between swims, and only touches the ground when told to sit.
        Activity.STANDING: Animation((FLOAT_A, FLOAT_B), fps=1.5),  # paddling slowly
        Activity.WALKING: Animation((SWIM_UP, FLOAT_A, SWIM_DOWN, FLOAT_A), fps=5),  # swimming
        Activity.SITTING: Animation((SIT_A, SIT_B), fps=1),  # resting on the bottom, nodding
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=8),  # paddling in protest
    },
    gait=Gait(speed=35, max_slope=0.7, distance=(100, 380)),
    locomotion=Locomotion.SWIM,
)
