"""The wolf: a gray wolf with amber eyes that trots around and howls now and then."""

from virtual_pet.behavior import Activity, Gait
from virtual_pet.i18n import QT_TRANSLATE_NOOP
from virtual_pet.species import Species
from virtual_pet.sprites import EYE, EYE_SHINE, Animation, art

STAND_A = art("""
    ................................
    ....................K...K.......
    ...................KDK.KBK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBDKBBKDDK...KBBKDDK.........
    .KDDDDKBBKDDK...KBBKDDK.........
    ..KDDKKBBKDDK...KBBKDDK.........
    ...KK.KBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBBKDDK..KBBBKDDK........
    .......KKKKKK....KKKKKK.........
    ................................
""")

STAND_B = art("""
    ................................
    ....................K...K.......
    ...................KDK.KBK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    ..KBBBKBBKDDK...KBBKDDK.........
    ..KBBBKBBKDDK...KBBKDDK.........
    ..KBBBKBBKDDK...KBBKDDK.........
    ..KDDDKBBKDDK...KBBKDDK.........
    ...KDDKBBKDDK...KBBKDDK.........
    ....KKKBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBBKDDK..KBBBKDDK........
    .......KKKKKK....KKKKKK.........
    ................................
""")

STAND_C = art("""
    ................................
    ....................K...........
    ...................KDK.KKK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBDKBBKDDK...KBBKDDK.........
    .KDDDDKBBKDDK...KBBKDDK.........
    ..KDDKKBBKDDK...KBBKDDK.........
    ...KK.KBBKDDK...KBBKDDK.........
    ......KBBKDDK...KBBKDDK.........
    ......KBBBKDDK..KBBBKDDK........
    .......KKKKKK....KKKKKK.........
    ................................
""")

WALK_0 = art("""
    ................................
    ....................K...K.......
    ...................KDK.KBK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBBBK.........
    .KBBBBKBBKDDK...KDDKBBK.........
    .KBBBBKBBKDDK...KDDKBBK.........
    .KBBBDKBBKDDK...KDDKBBK.........
    .KDDDKBBK.KDDK.KDDK.KBBK........
    ..KDDKBBK.KDDK.KDDK.KBBK........
    ...KKKBBK.KDDK.KDDK.KBBK........
    ....KBBK...KDDKDDK...KBBK.......
    ....KBBBK..KDDKDDDK..KBBBK......
    .....KKK....KKKKKK....KKK.......
    ................................
""")

WALK_1 = art("""
    ....................K...K.......
    ...................KDK.KBK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBDKBBKDDK...KBBKDDK.........
    .KDDDDKKBBKDK...KBBKKDDK........
    ..KDDK.KBBKDK...KBBKKDDK........
    ...KK...KBBKK...KBBKKDDK........
    ........KBBBK...KBBKKDDK........
    .........KKKK...KBBK.KK.........
    .........KDDDK..KBBBK...........
    ..........KKK....KKK............
    ................................
""")

WALK_2 = art("""
    ................................
    ....................K...K.......
    ...................KDK.KBK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBBBKKKKKBBBWWK.........
    .KBBBBKDDKBBK...KBBKDDK.........
    .KBBBBKDDKBBK...KBBKDDK.........
    .KBBBDKDDKBBK...KBBKDDK.........
    .KDDDDKDK.KBBK.KBBK.KDDK........
    ..KDDKDDK.KBBK.KBBK.KDDK........
    ...KKKDDK.KBBK.KBBK.KDDK........
    ....KDDK...KBBKBBK...KDDK.......
    ....KDDDK..KBBKBBBK..KDDDK......
    .....KKK....KKKKKK....KKK.......
    ................................
""")

WALK_3 = art("""
    ....................K...K.......
    ...................KDK.KBK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBDKBBKDDK...KBBKDDK.........
    .KDDDDKBBKKDDK...KBBKDK.........
    ..KDDKKBBKKDDK...KBBKDK.........
    ...KK.KBBK.KDDK..KBBKDK.........
    ......KBBK.KDDDK.KBBKDK.........
    ......KBBK..KKK...KKDDK.........
    ......KBBBK........KDDDK........
    .......KKK..........KKK.........
    ................................
""")

SIT_A = art("""
    ...................K...K........
    ..................KDK.KBK.......
    ..................KDDKKBWK......
    .................KDDDKBBWK......
    .................KDBBBBBBBKK....
    ................KBBBBBBBBBBBKKK.
    ................KBBBBEEBBBBBBNK.
    ...............KBBBBNHNBBBBBBNK.
    ..............KDLBBBBBBBKWWWWWK.
    ............KDKLLLBBBBWWWKKKKK..
    ...........KDDDKLLLLWWWWWWK.....
    ..........KDDDKLLLLWWWWKKK......
    ..........KDDDDKLLLWWWWK........
    .........KDDDDBBKLLWWWWK........
    .........KDDDBBBBBKLWWWK........
    ........KBDDDBBBBBBWWWWK........
    ........KBBDDBBBBBKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .KK...KBBBBBBBBBKDKBBKDDK.......
    KDDK..KBBBBBBBBBKDKBBKDDK.......
    KDDBKKKBBBBBBBBBKDKBBKDDK.......
    KDBBBBKBBBBBBBBKDDKBBKDDK.......
    .KBBBBKBBBBKKKKBBBKBBKDDK.......
    ..KBBBKBBBKBBBBBBBKBBBDDDK......
    ...KKKKKKKKKKKKKKKKKKKKKK.......
    ................................
""")

SIT_B = art("""
    .......................K........
    ..................KDK.KKK.......
    ..................KDDKKBWK......
    .................KDDDKBBWK......
    .................KDBBBBBBBKK....
    ................KBBBBBBBBBBBKKK.
    ................KBBBBEEBBBBBBNK.
    ...............KBBBBNHNBBBBBBNK.
    ..............KDLBBBBBBBKWWWWWK.
    ............KDKLLLBBBBWWWKKKKK..
    ...........KDDDKLLLLWWWWWWK.....
    ..........KDDDKLLLLWWWWKKK......
    ..........KDDDDKLLLWWWWK........
    .........KDDDDBBKLLWWWWK........
    .........KDDDBBBBBKLWWWK........
    ........KBDDDBBBBBBWWWWK........
    ........KBBDDBBBBBKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .KK...KBBBBBBBBBKDKBBKDDK.......
    KDDK..KBBBBBBBBBKDKBBKDDK.......
    KDDBKKKBBBBBBBBBKDKBBKDDK.......
    KDBBBBKBBBBBBBBKDDKBBKDDK.......
    .KBBBBKBBBBKKKKBBBKBBKDDK.......
    ..KBBBKBBBKBBBBBBBKBBBDDDK......
    ...KKKKKKKKKKKKKKKKKKKKKK.......
    ................................
""")

HOWL_A = art("""
    ..........................KK....
    ..................K......KNNK...
    .................KWBK...KBBBK...
    .................KWBBKKKBBBBWK..
    ...............K.KWBBBBBBBBBWK..
    ..............KDDKBBBBBBBBWK....
    ..............KDDDBBBBBBBWK.....
    ...............KDDBBEEBBWWK.....
    ...............KDLBNHNBWWWK.....
    ............KDKLLLBBBBWWWWK.....
    ...........KDDDKLLLLWWWWWWK.....
    ..........KDDDKLLLLWWWWKKK......
    ..........KDDDDKLLLWWWWK........
    .........KDDDDBBKLLWWWWK........
    .........KDDDBBBBBKLWWWK........
    ........KBDDDBBBBBBWWWWK........
    ........KBBDDBBBBBKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .KK...KBBBBBBBBBKDKBBKDDK.......
    KDDK..KBBBBBBBBBKDKBBKDDK.......
    KDDBKKKBBBBBBBBBKDKBBKDDK.......
    KDBBBBKBBBBBBBBKDDKBBKDDK.......
    .KBBBBKBBBBKKKKBBBKBBKDDK.......
    ..KBBBKBBBKBBBBBBBKBBBDDDK......
    ...KKKKKKKKKKKKKKKKKKKKKK.......
    ................................
""")

HOWL_B = art("""
    ..........................KK....
    ..................K......KNNK...
    .................KWBK...KBBBK...
    .................KWBBKKKBBBNNK..
    ...............K.KWBBBBBBBNNWWK.
    ..............KDDKBBBBBBBNNWWK..
    ..............KDDDBBBBBBNNWWK...
    ...............KDDBBEEBNWWK.....
    ...............KDLBNHNBWWWK.....
    ............KDKLLLBBBBWWWWK.....
    ...........KDDDKLLLLWWWWWWK.....
    ..........KDDDKLLLLWWWWKKK......
    ..........KDDDDKLLLWWWWK........
    .........KDDDDBBKLLWWWWK........
    .........KDDDBBBBBKLWWWK........
    ........KBDDDBBBBBBWWWWK........
    ........KBBDDBBBBBKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .......KBBBBBBBBKDKBBKDDK.......
    .KK...KBBBBBBBBBKDKBBKDDK.......
    KDDK..KBBBBBBBBBKDKBBKDDK.......
    KDDBKKKBBBBBBBBBKDKBBKDDK.......
    KDBBBBKBBBBBBBBKDDKBBKDDK.......
    .KBBBBKBBBBKKKKBBBKBBKDDK.......
    ..KBBBKBBBKBBBBBBBKBBBDDDK......
    ...KKKKKKKKKKKKKKKKKKKKKK.......
    ................................
""")

CARRIED_A = art("""
    ....................K...........
    ...................KDK.KKK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBDKBBKDDK...KBBKDDK.........
    .KDDDKBBKDDK.....KBBKDDK........
    ..KDDKBBKDDK.....KBBKDDK........
    ...KKKBBKDDK.....KBBKDDK........
    ....KBBKDDK.......KBBKDDK.......
    ....KBBKDDK.......KBBKDDK.......
    ....KBBKDDK.......KBBKDDK.......
    .....KK.KK.........KK.KK........
    ................................
""")

CARRIED_B = art("""
    ....................K...........
    ...................KDK.KKK......
    ...................KDDKKBWK.....
    ..................KDDDKBBWK.....
    ..................KDBBBBBBBKK...
    .................KBBBBBBBBBBBKKK
    .................KBBBBEEBBBBBBNK
    .........KKKKKKKKBBBBNHNBBBBBBNK
    .......KKDDDDDDDKLBBBBBBBKWWWWWK
    .....KKDDDDDDDDKLLLBBBBWWWKKKKK.
    ....KDDDDDDDDDDDKLLLLWWWWWWK....
    ...KDDKBBBDDDDDKLLLLWWWWKKK.....
    ..KDDBKBBBBBBDDDKLLLWWWWK.......
    ..KDBBKBBBBBBBBBBKBBWWWK........
    .KDBBBKBBBBWWWWWBBBBWWWK........
    .KBBBBKBBBKKKKKKKBBBWWK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBBKBBKDDK...KBBKDDK.........
    .KBBBDKBBKDDK...KBBKDDK.........
    .KDDDDKKBBKDDK.KBBKDDK..........
    ..KDDK.KBBKDDK.KBBKDDK..........
    ...KK..KBBKDDK.KBBKDDK..........
    ........KBBKDDKBBKDDK...........
    ........KBBKDDKBBKDDK...........
    .........KK.KK.KK.KK............
    ................................
    ................................
""")

WOLF = Species(
    key="wolf",
    label=QT_TRANSLATE_NOOP("Species", "Wolf"),
    palette={
        "K": "#2a2422",  # outline
        "B": "#988f85",  # gray coat
        "D": "#625952",  # dark saddle over the back, tail tip, far ear and legs
        "L": "#cbc2b5",  # pale gray ruff on the cheeks and neck
        "W": "#f0e6d4",  # cream: muzzle, throat, chest, belly, inner ear
        "N": "#1b1716",  # nose, rim of the eye, pupil, open mouth
        EYE: "#e9a53a",  # amber eye
        EYE_SHINE: "#e9a53a",  # amber eye, lower half: dark while blinking
    },
    animations={
        # Swaying its tail, twitching an ear now and then.
        Activity.STANDING: Animation((STAND_A, STAND_B, STAND_A, STAND_B, STAND_A, STAND_C), fps=2),
        Activity.WALKING: Animation((WALK_0, WALK_1, WALK_2, WALK_3), fps=8),  # trotting
        # Sitting up; every 8.5 s it raises its snout and howls.
        Activity.SITTING: Animation(
            (*[SIT_A] * 6, SIT_B, *[SIT_A] * 5, HOWL_A, HOWL_B, HOWL_B, HOWL_B, HOWL_A), fps=2
        ),
        Activity.CARRIED: Animation((CARRIED_A, CARRIED_B), fps=6),  # kicking, legs out and in
    },
    gait=Gait(speed=50, max_slope=0.4, distance=(100, 400)),
)
